<?php
/**
 * @var \Learncom\Models\LearnTest $test_model
 * @var \Learncom\Models\LearnTestFolder $folder
 */
?>

<a name="create_article" id="create_article" class="btn btn-primary pull-left">Back</a>
<hr>
<div class=" p-20 text-center">
    <div class=" list-courses-wrap list-courses-custom">
        <div class=" h-100 mt-xs-15 bg-white border-1-primary rounded mb-xs-70">
            <h2 id="txtName" class="text-main text-center text-uppercase">Bài thi: <?= $test_parent_model->getTestName() ?></h2>
            Số lỗi : <?=$score_model->getScoreTotalError() ?>
            <table class="table table-striped table-bordered">
                <thead class="table_header" >
                <tr class="headings">
                    <th  class="column-title">Thời gian </th>
                    <th  class="column-title">Hành động </th>
                </tr>
                </thead>

                <tbody class="tb_body">

                <?php
                $arrLog = $score_model->getScoreLog();
                $arrLog = json_decode($arrLog,true);
                foreach ($arrLog as $log) {
                    $arr_log = explode(',',$log);
                    ?>
                    <tr <?= $arr_log[1] == 3 || $arr_log[1] == 5 ? "style='color: red'" : ""?> >
                        <td class=" "><?php echo $this->my->formatDateTime($arr_log[0]) ?></td>
                        <td class=" "><?php echo $arr_log[2] ?></td>
                    </tr>

                <?php } ?>
                </tbody>
            </table>

        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('.carousel').carousel({
            touch: true,
            interval: false
        });
        window.onload = function() {
            var reloading = sessionStorage.getItem("reloading");
            if (reloading) {
                sessionStorage.removeItem("reloading");
                $('#subTest').submit();
            } else {
                sessionStorage.setItem("reloading", "true");
            }

        };
        $('#create_article').on('click',function () {
            history.back()
        })
    })
</script>