
<script>

    $(document).ready(function(){
        $("#create_form").submit(function(){
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Bạn cần nhập thông tin này');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Bạn cần nhập thông tin này');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }

            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });
        $('.file_image').on('click',function () {
            if ($('#image_1').hasClass('hidden')) {
                $('#image_2').addClass('hidden');
                $('#image_1').removeClass('hidden');
            } else {
                $('#image_1').addClass('hidden');
                $('#image_2').removeClass('hidden');
            }
        });
    });

</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-subject");?>'>List Subect</a><span class='divider'>/</span></li><li><a href='<?php echo $this->url->get("dashboard/create-subject");?>'>Create Sbject</a></li>");
</script>
<?php
if(!empty($formData['message']))
{
    ?>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $formData['typeMessage']?>">
        <?php echo $formData['message']; ?>
    </p>
<?php }	?>
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i><?= isset($formData['mode']) ? $formData['mode'] : "" ?> Môn Học :</h2>
            <div class="box-icon"> <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a> <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a> <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a> </div>
        </div>
        <div class="box-content">
            <form novalidate="novalidate" class="form-horizontal" id="create_form" action=""  enctype="multipart/form-data" method="post">
                <fieldset>
                    <div class="control-group">
                        <label class="control-label" for="slcClass">Môn Chính </label>
                        <div class="controls">
                            <select  id="slcParentId" name="slcParentId" class="class-subject ">
                                <option value=0> Chọn môn chính</option>
                                <?= isset($select_subject) ? $select_subject : "" ?>
                            </select>

                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="focusedInput">Name <em style="color:red;">*</em></label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['subject_name']) ? $formData['subject_name'] : ""?>" maxlength="256" id="txtName" name="txtName" class="input-xlarge focused"  type="text" >
                            <div class="text-danger msg-name"><?php echo isset($messages["subject_name"]) ? $messages["subject_name"] : "";?></div>

                        </div>
                    </div>
                    <div id="image_1" class="control-group">
                        <label class="control-label" for="upload-files">Image<em style="color:red;">*</em></label>
                        <div class="controls">
                            <input id="fileUpload" name="fileUpload" type="file"
                                   accept="<?php
                                   foreach($this->globalVariable->acceptUploadTypes as $k => $v)
                                   {
                                       echo $k.",";
                                   } ?>"  />
                            <button type="button" class="file_image">Uploadfile / link</button>
                            <div class="text-danger msg-image"><?php echo isset($messages["subject_image"]) ? $messages["subject_image"] : "";?></div>
                        </div>
                    </div>
                    <div id="image_2" class="control-group hidden">
                        <label class="control-label" for="focusedInput">Image <em style="color:red;">*</em></label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['subject_image']) ? $formData['subject_image'] : ""?>" maxlength="256" id="txtImage" name="txtImage" class="input-xlarge focused"  type="text" >
                            <button type="button" class="file_image">Uploadfile / link</button>

                        </div>
                        <div class="text-danger msg-image"><?php echo isset($messages["subject_image"]) ? $messages["subject_image"] : "";?></div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Order <em style="color:red;">*</em> </label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['subject_order']) ? $formData['subject_order'] : "" ?>" id="txtOrder" name="txtOrder" class="input-xlarge focused"    maxlength="10"  type="text" >
                            <div class="text-danger msg-order"><?php echo isset($messages["subject_order"]) ? $messages["subject_order"] : "";?></div>

                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" id="submit_create">Save changes</button>
                        <a id="edit_page" class="btn" href="<?php echo $this->url->get('dashboard/list-subject');?>"> Cancel </a> </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>
