<?php
/**
 * @var $parent_keyword;
 * @var \Learncom\Models\LearnArticle[] $related_articles
 * @var \Learncom\Models\LearnArticle $article
 */
?>
<main data-aos="fade-in">
    <section id="course-details" data-aos="fade-up">
        <div class="infoCourse_top">
            <div class="container">
                <h2>
                    <?= $article['article_icon'] ?>
                </h2>
                <p>
                    <?= $article['article_name'] ?>
                </p>
            </div>
        </div>
        <div class="container">
            <div class="row pt-50">
                <div class="col-lg-8 course-left">
                    <h3 style="margin-top:0px">THỜI KHÓA BIỂU</h3>
                    <div class="course-details-img text-center">
                        <img src="<?= $article['article_content'] ?>" alt="Course">
                    </div>
                    <?= $article['article_summary'] ?>
                </div>
                <div class="col-lg-4 course-right">
                    <?= $article['article_content_left'] ?>

                </div>
            </div>
        </div>
    </section>
</main>