<?php
/**
 * @var $parent_keyword;
 * @var \Learncom\Models\LearnArticle[] $related_articles
 * @var \Learncom\Models\LearnArticle $article
 */
?>
<main data-aos="fade-in">
    <section id="course-details" data-aos="fade-up">

        <div class="infoCourse_top">
            <div class="container">
                <h2>
                    <?= $article['article_name'] ?>
                </h2>
                <p>
                    <?= $article['article_summary'] ?>
                </p>
            </div>
        </div>
        <div class="container">
            <div class="row pt-50">
                <div class="col-lg-12 ">

                    <div class="course-details-img text-center">
                        <img src="<?= $article['article_content'] ?>" alt="Course">

                    </div>

                </div>

            </div>
        </div>
    </section>
</main>