<?php
/**
 * @var $parent_keyword;
 * @var \Learncom\Models\LearnArticle[] $articles
 */
?>

<main data-aos="fade-in">
        <div class="infoCourse_top">
            <div class="container">
                <h2>Thông tin tuyển sinh</h2>
                <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium.</p>
            </div>
        </div>
        <section class="container infoCourse_wrapper" data-aos="fade-up">
            <div class="row" data-aos="zoom-in" data-aos-delay="100">
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                    <div class="infoCourse_item">
                        <img src="https://bootstrapmade.com/demo/templates/Mentor/assets/img/course-2.jpg" alt="Course" />
                        <div class="infoCourse_content">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4>Vật lý 10</h4>
                            </div>
                            <h3>
                                <a href="#">Khóa học vật lý 10</a>
                            </h3>
                            <p>Xuất phát từ nhu cầu học thêm môn toán của các em học sinh để chuẩn bị kiến thức cho kỳ thi vào lớp 10 vô cùng khốc liệt ở Hà Nội, CMath đã cùng với các thầy cô giáo</p>
                            <div>
                                <div class="trainer-rank d-flex align-items-center">
                                    <i class='bx bxs-calendar'></i>
                                    <span>19/02/2023</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                    <div class="infoCourse_item">
                        <img src="https://bootstrapmade.com/demo/templates/Mentor/assets/img/course-2.jpg" alt="Course" />
                        <div class="infoCourse_content">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4>Vật lý 10</h4>
                            </div>
                            <h3>
                                <a href="#">Khóa học vật lý 10</a>
                            </h3>
                            <p>Xuất phát từ nhu cầu học thêm môn toán của các em học sinh để chuẩn bị kiến thức cho kỳ thi vào lớp 10 vô cùng khốc liệt ở Hà Nội, CMath đã cùng với các thầy cô giáo</p>
                            <div>
                                <div class="trainer-rank d-flex align-items-center">
                                    <i class='bx bxs-calendar'></i>
                                    <span>19/02/2023</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                    <div class="infoCourse_item">
                        <img src="https://bootstrapmade.com/demo/templates/Mentor/assets/img/course-2.jpg" alt="Course" />
                        <div class="infoCourse_content">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4>Vật lý 10</h4>
                            </div>
                            <h3>
                                <a href="#">Khóa học vật lý 10</a>
                            </h3>
                            <p>Xuất phát từ nhu cầu học thêm môn toán của các em học sinh để chuẩn bị kiến thức cho kỳ thi vào lớp 10 vô cùng khốc liệt ở Hà Nội, CMath đã cùng với các thầy cô giáo</p>
                            <div>
                                <div class="trainer-rank d-flex align-items-center">
                                    <i class='bx bxs-calendar'></i>
                                    <span>19/02/2023</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                    <div class="infoCourse_item">
                        <img src="https://bootstrapmade.com/demo/templates/Mentor/assets/img/course-2.jpg" alt="Course" />
                        <div class="infoCourse_content">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4>Vật lý 10</h4>
                            </div>
                            <h3>
                                <a href="#">Khóa học vật lý 10</a>
                            </h3>
                            <p>Xuất phát từ nhu cầu học thêm môn toán của các em học sinh để chuẩn bị kiến thức cho kỳ thi vào lớp 10 vô cùng khốc liệt ở Hà Nội, CMath đã cùng với các thầy cô giáo</p>
                            <div>
                                <div class="trainer-rank d-flex align-items-center">
                                    <i class='bx bxs-calendar'></i>
                                    <span>19/02/2023</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
</main>