<?php
use Learncom\Repositories\ClassSubject;
if(isset($msg_result['status']))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>

    <div class="box-content">
        <h3>Danh sách Phần quyền các nhóm: </h3>
        <form name="read_form" id="read_form0" method="post" >
        <table  style="table-layout: fixed" class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center; width: 15%">Tên</th>
                <th style="text-align:center; width: 20%"></th>
            </tr>
            </thead>
            <tbody>
                <tr style="border-color: grey">
                    <td  style="text-align:center;"  class="center">
                        <input style="height: 100%" id="txtName" name="txtName0">
                    </td>
                    <td  style="text-align:center;" class="center">
                        <button id="sbmSave0" name="sbmSubmit" value="0" data-browse="0" class="btn btn-danger btnSubmit" href="">Tạo</button>
                    </td>
                </tr>
            <?php
            foreach($list_item->items as  $item){
                ?>
                <script>
                    $(function(){
                        $('#delete<?= $item->getGroupId()?>').live("click",function(e){
                            e.preventDefault();
                            $('#warn').modal('show');
                            var id=$("#<?= $item->getGroupId();?>").attr("data-browse");
                            $("#class_id").val(id);
                            var str="Bạn của muốn xóa nhóm "+"<?php echo $item->getGroupName(); ?>";
                            $("#message").text(str);

                        });
                    });
                </script>
                <tr>
                        <td  id="<?= $item->getGroupId();?>" data-browse="<?= $item->getGroupId();?>" style="text-align:center;"  class="center">
                            <input style="height: 100%"  id="txtName<?= $item->getGroupId()?>" name="txtName<?= $item->getGroupId()?>" value="<?=$item->getGroupName() ?>">
                        </td>
                        <td  style="text-align:center;"class="center">
                            <button value="<?= $item->getGroupId()?>" id="sbmSave<?= $item->getGroupId()?>" name="sbmSubmit" data-browse="<?= $item->getGroupId()?>" class="btn btn-danger btnSubmit" href="">Lưu</button>
                            <a id="delete<?= $item->getGroupId()?>" class="btn btn-danger" href="">delelte</a>

                        </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        </form>
    </div>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="class_id" name="class_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<script>
    $(document).ready(function() {
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('/dashboard/delete-group-subject');?>";
            var id= $("#class_id").val();
            str=str.concat("?id=").concat(id);
            $('#delete').attr("href",str);
        });
       $('.btnSubmit').on('click',function () {
           var id = $(this).attr('data-browse');
           $('#read_form'+id).submit();
       })

    });
</script>