
<script>

    $(document).ready(function(){
        $("#create_form").submit(function(){
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Bạn cần nhập thông tin này');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Bạn cần nhập thông tin này');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if($('input[name=txtTime]').val() == '') {
                $('.msg-time').text('Bạn cần nhập thông tin này');
                $('#txtTime').addClass("border-red");
                valid = false;
            } else {
                $('.msg-time').text('');
                $('#txtTime').removeClass("border-red");
            }
            if($('input[name=txtNumberQuestion]').val() == '') {
                $('.msg-number-question').text('Bạn cần nhập thông tin này');
                $('#txtNumberQuestion').addClass("border-red");
                valid = false;
            } else {
                $('.msg-number-question').text('');
                $('#txtNumberQuestion').removeClass("border-red");
            }
            if($('select[name=slcClass]').val() == '') {
                $('.msg-class').text('Bạn cần nhập thông tin này');
                $('#slcClass').addClass("border-red");
                valid = false;
            } else {
                $('.msg-class').text('');
                $('#slcClass').removeClass("border-red");
            }
            if($('select[name=slcSubject]').val() == '') {
                $('.msg-subject').text('Bạn cần nhập thông tin này');
                $('#slcSubject').addClass("border-red");
                valid = false;
            } else {
                $('.msg-subject').text('');
                $('#slcSubject').removeClass("border-red");
            }
            if($('#txtNumberOf').val() != "" && parseInt($('#txtNumberOf').val()) >15 ) {
                $('.msg-number-of').text('Không được lớn hơn 15');
                $('#txtNumberOf').addClass("border-red");
            } else {
                $('.msg-number-of').text("");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });
    });

</script>
<?php
if(!empty($formData['message']))
{
    ?>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $formData['typeMessage']?>">
        <?php echo $formData['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form class="form-horizontal form-label-left" id="create_form" action=""  enctype="multipart/form-data" method="post">
                    <h4>Note</h4>
                    -Nếu số hình ảnh câu hỏi lớn hơn đáp án, mặc định là số câu lơn hơn đó là tự luận
                    <br>
                    -Nếu Đề thi có cả trắc nghiệm và tự luận thì tên của tự luận phải lớn hơn trắc nghiệm (Ví dụ: Trắc nghiệm từ: Img001.PNG tới Img020.PNG, thì tự luận phải là Img021.PNG trở đi)
                    
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="slcClass">Lớp <em style="color:red;">*</em></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select  id="slcClass" name="slcClass" class="form-control class-subject <?php echo isset($messages["test_class_id"]) ? $messages["status"] : "";?>">
                                        <?= isset($select_class) ? $select_class : "" ?>
                                    </select>
                                    <div class="text-danger msg-class"><?php echo isset($messages["test_class_id"]) ? $messages["test_class_id"] : "";?></div>

                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="slcSubject">Môn học <em style="color:red;">*</em></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select  id="slcSubject" name="slcSubject" class="form-control class-subject <?php echo isset($messages["test_subject_id"]) ? $messages["status"] : "";?>">
                                        <option value="">Chọn Môn học</option>
                                        <?= isset($select_subject) ? $select_subject : "" ?>
                                    </select>
                                    <div class="text-danger msg-subject"><?php echo isset($messages["test_subject_id"]) ? $messages["test_subject_id"] : "";?></div>

                                </div>
                            </div>

                    <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="focusedInput">Tên <em style="color:red;">*</em></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input value="<?php echo isset($formData['test_name']) ? $formData['test_name'] : ""?>"
                                       maxlength="256" id="txtName" name="txtName" class="form-control focused <?php echo isset($messages["test_name"]) ? $messages["status"] : "";?>"  type="text" >
                                <div class="text-danger msg-name"><?php echo isset($messages["test_name"]) ? $messages["test_name"] : "";?></div>

                            </div>
                        </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="selectError">Các Lớp Thi </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?= isset($select_school_class) ? $select_school_class : "" ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Thời gian bắt đầu thi   </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php
                            $banner_start_time = "";
                            if (isset($formData["test_time_start"])){
                                $banner_start_time = $formData["test_time_start"];
                            }
                            if ($banner_start_time != 0 || !empty($banner_start_time)){
                                $banner_start_time = date('m/d/Y H:i', $banner_start_time+$this->globalVariable->timeZone);
                            } else {
                                $banner_start_time = "";
                            }
                            ?>
                            <input value="<?php echo $banner_start_time ?>" type="text" id="txtStartTime"
                                   data-timepicker="true"  placeholder="MM/DD/YYYY HH:MM" data-time-format='hh:ii' name="txtStartTime"
                                   class="form-control col-md-7 col-xs-12 datepicker-here <?php echo isset($messages["test_time_start"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-start-time"><?php echo isset($messages["test_time_start"]) ? $messages["test_time_start"] : ""; ?></span>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Bắt đầu thi </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radStatus"
                                                                  value="N" <?php echo (isset($formData["test_status"]) && $formData["test_status"] == "N") ? "checked" : ''; ?>>Chưa Thi<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radStatus"
                                                                  value="P" <?php echo (isset($formData["test_status"]) && $formData["test_status"] == "P") ? "checked" : ''; ?>>Đang Thi<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radStatus"
                                                                  value="S" <?php echo (isset($formData["test_status"]) && $formData["test_status"] == "S") ? "checked" : ''; ?>>Thi Xong<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                        <div <?= (isset($formData['mode']) && $formData['mode'] == 'Chỉnh Sửa') ? 'hidden' : "" ?>>
                            <div id="image_1" class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="upload-files">Câu hỏi<em style="color:red;">*</em></label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input  id="fileUpload" name="fileUpload[]" type="file" multiple="multiple"
                                            accept="<?php
                                            foreach($this->globalVariable->acceptUploadTypes as $k => $v)
                                            {
                                                echo $k.",";
                                            } ?>"  />
                                    <div class="text-danger msg-image"><?php echo isset($messages["image"]) ? $messages["image"] : "";?></div>
                                </div>
                                <div class="col-md-2 col-sm-2 col-xs-12">
                                    <button type="button" class="file_image">Uploadfile / link</button>
                                </div>
                            </div>
                            <div id="image_2" class="form-group hidden" >
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="focusedInput">Link Câu hỏi <em style="color:red;">*</em></label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input maxlength="256" id="image" name="image" class=" form-control focused <?php echo isset($messages["image"]) ? $messages["status"] : "";?>"  type="text"
                                           value="<?php echo isset($formData['test_link']) ? $formData['test_link'] : "";?>">
                                    <div class="text-danger msg-image"><?php echo isset($messages["test_link"]) ? $messages["test_link"] : "";?></div>
                                </div>
                                <div class="col-md-2 col-sm-2 col-xs-12">
                                    <button type="button" class="file_image">Uploadfile / link</button>
                                </div>
                            </div>

                            <div id="comment_1" class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="upload-files">Hướng dẫn giải</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="fileUploadComment" name="fileUploadComment[]" type="file" multiple="multiple"
                                           accept="<?php
                                           foreach($this->globalVariable->acceptUploadTypes as $k => $v)
                                           {
                                               echo $k.",";
                                           } ?>"  />
                                </div>
                            </div>
                            <div id="comment_2" class="form-group hidden" >
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="focusedInput">Link Hướng dẫn giải <em style="color:red;">*</em></label>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input maxlength="256" id="imageComment" name="imageComment" class="form-control focused "  type="text"
                                           value="<?php echo isset($formData['test_link_comment']) ? $formData['test_link_comment'] : "";?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Số Câu Hỏi <em style="color:red;">*</em> </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input <?= (isset($formData['mode']) && $formData['mode'] == 'Chỉnh Sửa') ? 'disabled' : "" ?> value="<?php echo isset($formData['test_number_question']) ? $formData['test_number_question'] : "" ?>"
                                           id="txtNumberQuestion" name="txtNumberQuestion" class="form-control focused  <?= isset($messages["test_number_question"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                                    <div class="text-danger msg-number-question"><?php echo isset($messages["test_number_question"]) ? $messages["test_number_question"] : "";?></div>

                                </div>
                            </div>
                            <div id="daode" class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Số Đề Thi <em style="color:red;">*</em> </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input <?= (isset($formData['mode']) && $formData['mode'] == 'Chỉnh Sửa') ? 'disabled' : "" ?> value="<?php echo isset($formData['test_number_exam']) ? $formData['test_number_exam'] : "" ?>"
                                           id="txtNumberOf" name="txtNumberOf"
                                           class="form-control focused  <?= isset($messages["test_number_exam"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                                    *Nếu không cần đảo đề thì điền 1.(Số đề đảo hạn chế lớn hơn 15)
                                    <div class="text-danger msg-number-of"><?php echo isset($messages["test_number_exam"]) ? $messages["test_number_exam"] : "";?></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Số Điểm cho trắc nghiệm <em style="color:red;">*</em> </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input value="<?php echo isset($formData['test_score_choose']) ? $formData['test_score_choose'] : "" ?>"
                                       id="txtScroreChoose" name="txtScroreChoose"
                                       class="form-control focused  <?= isset($messages["test_score_choose"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                                *Nếu tất cả là trắc nghiệm thì số điểm cho trắc nghiệm là : 10, ngược lại, nếu tự luận: 0
                                <div class="text-danger msg-number-question"><?php echo isset($messages["test_score_choose"]) ? $messages["test_score_choose"] : "";?></div>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Thơi Gian Thi (phút) <em style="color:red;">*</em> </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input value="<?php echo isset($formData['test_time']) ? $formData['test_time'] : "" ?>"
                                       id="txtTime" name="txtTime" class="form-control focused  <?= isset($messages["test_time"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                                <div class="text-danger msg-time"><?php echo isset($messages["test_time"]) ? $messages["test_time"] : "";?></div>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <em style="color:red;">*</em> </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input value="<?php echo isset($formData['test_order']) ? $formData['test_order'] : "" ?>"
                                       id="txtOrder" name="txtOrder" class="form-control focused  <?= isset($messages["test_order"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                                <div class="text-danger msg-order"><?php echo isset($messages["test_order"]) ? $messages["test_order"] : "";?></div>
                            </div>
                        </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Số Lần Thi </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radOnlyOne"
                                                                  value="Y" <?php echo (isset($formData["test_only_one"]) && $formData["test_only_one"] == "Y") ? "checked" : ''; ?>>một lần<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radOnlyOne"
                                                                  value="N" <?php echo (isset($formData["test_only_one"]) && $formData["test_only_one"] == "N") ? "checked" : ''; ?>>Không giới hạn<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Xem Đáp Án </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsPublicAnswer"
                                                                  value="Y" <?php echo (isset($formData["test_is_public_answer"]) && $formData["test_is_public_answer"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsPublicAnswer"
                                                                  value="N" <?php echo (isset($formData["test_is_public_answer"]) && $formData["test_is_public_answer"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Xem Điểm Thi </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsPublicScore"
                                                                  value="Y" <?php echo (isset($formData["test_public_score"]) && $formData["test_public_score"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsPublicScore"
                                                                  value="N" <?php echo (isset($formData["test_public_score"]) && $formData["test_public_score"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($formData["test_active"]) && $formData["test_active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["test_active"]) && $formData["test_active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtContent">Lời Nhắc nhở </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class=" <?= isset($messages["test_description"]) ? $messages["status"] : "";?>" style="width: 500px;height: 200px" id="txtDescription" name="txtDescription"><?php echo isset($formData['test_description']) ? $formData['test_description'] : "" ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtContent">Đáp Án </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class=" <?= isset($messages["test_answer_decode"]) ? $messages["status"] : "";?>" placeholder="1:A,2:B,3:C,4:A" style="width: 500px;height: 200px" id="txtAnswer" name="txtAnswer"><?php echo isset($formData['test_answer_decode']) ? $formData['test_answer_decode'] : "" ?></textarea>
                                <div class="text-danger"><?php echo isset($messages["test_answer_decode"]) ? $messages["test_answer_decode"] : "";?></div>
                            </div>
                        </div>
                        <script type="text/javascript">
                            window.onload = function () {
                                var oFCKeditor2 = new FCKeditor('txtAnswer');
                                oFCKeditor2.Height = '500';
                                oFCKeditor2.Width = '650';
                                oFCKeditor2.ToolbarSet = "Default";
                                oFCKeditor2.Basepath = '../backend/fckeditor/';
                                oFCKeditor2.ReplaceTextarea();
                            }
                        </script>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmType" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/office/list-new-test"); ?>">Cancel</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<script>
    $('.class-subject').on('change',function () {
        var subject_id = $('#slcSubject').val();
        var class_id = $('#slcClass').val();
        var group_id = '<?= isset($formData['test_group_id']) ? $formData['test_group_id'] : 0 ?>';
        $.ajax({
            url: "<?php echo $this->url->get("/dashboard/get-group-test")?>",
            async: false,
            type: "POST",
            dataType: "JSON",
            data: {'subject_id': subject_id,
                'class_id' : class_id,
                'group_id' : group_id,
            },
            success: function(data){
                $('#slcGroup').html('<option value=0>Chọn Khóa</option>'+data);
            }
        });
    }).trigger('change');
    $('.file_image').on('click',function () {
        if ($('#image_1').hasClass('hidden')) {
            $('#image_2').addClass('hidden');
            $('#image_1').removeClass('hidden');
            $('#daode').removeClass('hidden disable');
            $('#comment_2').addClass('hidden');
            $('#comment_1').removeClass('hidden');
        } else {
            $('#image_1').addClass('hidden');
            $('#image_2').removeClass('hidden');
            $('#daode').addClass('hidden disable');
            $('#comment_1').addClass('hidden');
            $('#comment_2').removeClass('hidden');
        }
    });

</script>