<?php
/**
 * @var $blog_keyword;
 * @var \Learncom\Models\LearnArticle[] $blogs
 *  @var \Learncom\Models\LearnMenu[] $menus
 */
$arrClass = \Learncom\Models\LearnClass::find([
    'order' => 'class_order ASC'
]);
$arrSubject = \Learncom\Models\LearnSubject::find([
    'subject_parent_id = 0',
    'order' => 'subject_order ASC'
]);
?><main>
    <?php if (count($banners) > 0) { ?>
        <div class="banner-custom">
            <div id="carousel-banner" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <?php foreach ($banners as $key => $banner) { ?>
                        <div class="carousel-item <?= $key == 0 ? 'active' : '' ?>">
                            <img class="d-block w-100" src="<?=  $banner['banner_image']  ?>" alt="" title="">
                            <div class="carousel-caption d-none d-md-block">
                                <?= $banner['banner_content'] ?>
                            </div>
                        </div>
                    <?php } ?>
                <?php if (count($banners) > 1) { ?>
                    <a class="carousel-control-prev" href="#carousel-banner" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-banner" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
    <div class="padding-block">
        <div class="container">
            <div class="row">
                <?php
                $arrSubject = \Learncom\Models\LearnSubject::find([
                    'order' => 'subject_order ASC',
                    'subject_parent_id = 0 AND (subject_image != "" AND subject_image IS NOT NULL)',
                ]);
                foreach ($arrSubject as $subject) {
                ?>
                <div class="col-lg-<?=12/(count($arrSubject)) ?> mt-xs-30">
                    <div class="item-mon-hoc">
                        <img src="<?= $subject->getSubjectImage() ?>" alt="<?=$subject->getSubjectName() ?>" title="<?=$subject->getSubjectName() ?>">
                        <div class="box-hover-mon-hoc">
                            <h4 class="title-mon-hoc"><img src="<?php echo $this->url->getStatic('frontend/')?>images/calculator-solid.svg" alt="" class="mr-10"><?=$subject->getSubjectName() ?></h4>
                            <?php
                            $arrTestToan = \Learncom\Repositories\Test::findBySubject($subject->getSubjectId());
                            foreach ($arrTestToan as $test) {
                            ?>
                                <a href="/start-test?classId=<?= $test->getTestClassId()?>&subjectId=<?= $test->getTestSubjectId()?>&testId=<?=$test->getTestId() ?>">
                                    <p class="text-white mt-10">
                                        <?=$test->getTestName()?>
                                     </p>
                                </a>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="banner-commit">
        <h2 class="text-white text-30 font-weight-bold text-center">
            <?php foreach ($menus as $menu) {
                if ($menu['menu_type'] == 'default'){
                    echo $menu['menu_name'];
                }
            }
             ?>
        </h2>
        <div class="line-bottom-bolder mx-auto"></div>
        <div id="carousel-banner-commit" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <?php
                $arrTeacher = \Learncom\Models\LearnUser::find('user_role = "teacher" AND user_active = "Y"');
                $t= 0 ;
                foreach ($arrTeacher as $teacher) {
                ?>
                <div class="carousel-item <?=$t==0 ? "active" : ""  ?>">
                    <div class="carousel-caption">
                        <p class="text-white text-center text-xs-left"><?= $teacher->getUserDescription() ?></p>
                        <div class="info-teacher mt-20">
                            <span class="img-teacher mr-10"><img src="<?php echo $this->url->getStatic('frontend/')?>images/img-teacher.jpg" alt="Giáo viên" title="Giáo viên"></span>
                            <span class="d-inline-block text-left text-xs-center text-xs-14"><strong><?= $teacher->getUserName() ?></strong><br>Giáo viên <?=$teacher->getUserAddress() ?></span>
                        </div>
                    </div>
                </div>
                <?php $t++ ;} ?>
            </div>
            <a class="carousel-control-prev" href="#carousel-banner-commit" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-banner-commit" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="padding-block">
        <div class="container">
            <h2 class="text-main text-30 font-weight-bold text-center">
                <?php foreach ($menus as $menu) {
                    if ($menu['menu_type'] == 'course'){
                        echo $menu['menu_name'];
                    }
                }
                ?>
            </h2>
            <div class="line-bottom-bolder mx-auto mb-10"></div>
            <div class="row mt-20">
                <?php
                    $menuExcluded = '';
                    foreach ($menus as $menu) {
                        if ($menu['menu_type'] == 'course'){
                            if ($menu['menu_excluded']) {
                                $menuExcluded = $menu['menu_excluded'];
                            }
                        }
                    }
                    $count = 0;

                    foreach ($arrClass as $class){
                        if ($count > 3){
                            break;
                        }
                        foreach ($arrSubject as $subject){
                            if (!in_array($class->getClassId() . '-' . $subject->getSubjectId(), explode(',',$menuExcluded))){
                                $count++;
                ?>
                                <div class="col-lg-3 mt-20">
                                    <div class="box-course">
                                        <div class="img-course">
                                            <a href="<?php echo $this->url->get('/khoahoc?classId='.$class->getClassId().'&subjectId='.$subject->getSubjectId()) ?>"><img src="<?php echo $this->url->getStatic('frontend/')?>images/toan-10.jpg" alt="Khóa học" title="Khóa học"></a>
                                        </div>
                                        <div class="content-course">
                                            <div>
                                                <h2 class="text-20"><a href="" target="_self" class="text-main"><?php echo $subject->getSubjectName().' '.$class->getClassName() ?></a></h2>
                                                <p>Các khóa học <?php echo $subject->getSubjectName().' '.$class->getClassName() ?></p>
                                            </div>
                                            <a href="<?php echo $this->url->get('/khoahoc?classId='.$class->getClassId().'&subjectId='.$subject->getSubjectId()) ?>" target="_self" title="" class="btn btn-main h-50px text-18">Chi Tiết</a>
                                        </div>
                                    </div>
                                </div>
                <?php
                           if ($count > 3){
                               break;
                           } }}} ?>
            </div>
        </div>
    </div>
    <?php if (sizeof($blogs) > 0) { ?>
        <div class="padding-block bg-white mt-10">
            <div class="container">
                <h2 class="text-main text-30 font-weight-bold text-center">
                    <?php foreach ($menus as $menu) {
                        if ($menu['menu_type'] == 'blog'){
                            echo $menu['menu_name'];
                        }
                    }
                    ?>
                </h2>
                <div class="line-bottom-bolder mx-auto mb-10"></div>
                <div class="row mt-20">
                    <?php foreach ($blogs as $blog) { ?>
                        <div class="col-lg-4 mt-20">
                        <div class="box-blog">
                            <div class="img-blog">
                                <a href="<?php echo $this->url->get('/'.$blog_keyword.'/'.$blog->getArticleKeyword()) ?>" target="_self" title=""><img src="<?php echo $blog->getArticleIcon() ?>" alt="" title=""></a>
                            </div>
                            <div class="content-blog p-15">
                                <h3><a href="" target="_self" title="" class="text-main"><?php echo $blog->getArticleName() ?></a></h3>
                                <div class="line-bottom-bolder-2 mb-10"></div>
                                <p class="text-14"><?php echo $blog->getArticleSummary() ?></p>
                                <a href="<?php echo $this->url->get('/'.$blog_keyword.'/'.$blog->getArticleKeyword()) ?>" target="_self" title="" class="d-block text-right text-main">Xem thêm</a>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <p class="mt-30 text-center"><a href="<?php echo $this->url->get('/blogs')?>" target="_self" title="" class="btn btn-white d-xs-block shadow-1">Xem Thêm</a></p>
            </div>
        </div>
    <?php } ?>
</main>