<footer>
    <div class="footer_main">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <a href="" class="d-block text-xs-center mb-10"><img src="<?php echo $this->url->getStatic('frontend/') ?>images/logo.png" alt="Logo"></a>
                </div>
                <div class="col-lg-2 d-none d-lg-block">
                    <h2>MENU</h2>
                    <ul class="list-unstyled list-menu-footer">
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Trang chủ</a></li>
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Liên kết</a></li>
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Bài giảng</a></li>
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Trắc nghiệm</a></li>
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Đăng nhập</a></li>
                        <li><a href=""><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-arrow-left.svg" alt="">Tài liệu</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h2>LIÊN HỆ</h2>
                    <ul class="list-unstyled list-menu-footer">
                        <li><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-address-white.svg" alt="">Cơ sở 1: 15 Trần Hưng Đạo, TP. Phan Thiết</li>
                        <li><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-address-white.svg" alt="">Cơ sở 2: 44 Bùi Thị Xuân, TP. Phan Thiết</li>
                        <li><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-phone-white.svg" alt="">0983.664.523 (Thầy Hải)</li>
                        <li><img src="<?php echo $this->url->getStatic('frontend/') ?>images/icon-phone-white.svg" alt="">0988.475.362 (Cô Phương)</li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h2>Bản đồ</h2>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.2873203683994!2d108.10198881526081!3d10.941655259112933!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317683197f2c5955%3A0x20a55df76bcedc86!2zMTUgVHLhuqduIEjGsG5nIMSQ4bqhbywgUGjDuiBUaHXhu7csIFRow6BuaCBwaOG7kSBQaGFuIFRoaeG6v3QsIELDrG5oIFRodeG6rW4sIFZpZXRuYW0!5e0!3m2!1sen!2s!4v1630465656964!5m2!1sen!2s" width="600" height="250" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>
        </div>
    </div>
</footer>
<div id="l-loading" style="position: fixed;z-index: 10000;top: 0;left: 0;width: 100%;height: 100%;filter: alpha(opacity=85);opacity: 1;text-align: center;display:none;">
    <div style="background-color: rgba(255, 255, 255, 0.9);width: 100%;height: 100%;">
        <img src="<?php echo $this->url->getStatic('frontend/images/waiting.gif'); ?>" alt='' title='' style="vertical-align:middle;position: relative;z-index: 10001;top: calc(50% - 16px)">
    </div>
</div>

<script src="<?php echo $this->url->getStatic('frontend/') ?>js/jquery-3.5.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/') ?>js/popper.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/') ?>js/bootstrap-4.5.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/lazysizes.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/ls.bgset.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/style.js?v=<?php echo time(); ?>"></script>
<script>
    const ASSETS = {};
    for (var __i = 0; __i < commands.length; __i++) {
        commands[__i]();
    }
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div id="qr-block" class="qr-block">
    <i class="fa fa-qrcode" aria-hidden="true"></i>
    <span id="close-qr" class="icon-close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </span>
</div>
<div id="qr-info" class="qr-info">
    <span id="close-qr-info" class="icon-close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </span>
    <div id="qr-link" alt="qr"></div>
    <button class="btn-primary" id="copy-qr" style="width: 200px;margin-top: -10px;">Download QR</button>
</div>
<div id="canvas"></div>
<script type="text/javascript" src="https://unpkg.com/qr-code-styling@1.5.0/lib/qr-code-styling.js"></script>

<script>
    var url = window.location.href;
    let qrCode = new QRCodeStyling(
     {
    "width": 200,
    "height": 200,
    "data": url,
    "margin": 10,
    "qrOptions": {
        "typeNumber": "0",
        "mode": "Byte",
        "errorCorrectionLevel": "Q"
    },
    "imageOptions": {
        "hideBackgroundDots": true,
        "imageSize": 0.4,
        "margin": 0
    },
    "dotsOptions": {
        "type": "extra-rounded",
        "gradient": {
            "type": "radial",
            "rotation": 0.17453292519943295,
            "colorStops": [
                {
                    "offset": 0,
                    "color": "#121112"
                },
                {
                    "offset": 1,
                    "color": "#07082c"
                }
            ]
        }
    },
    "backgroundOptions": {
        "color": "#ffffff"
    },
    "image": "<?php echo $this->url->getStatic('frontend/'); ?>/images/logo.png",
    "dotsOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#6a1a4c",
            "color2": "#6a1a4c",
            "rotation": "0"
        }
    },
    "cornersSquareOptions": {
        "type": "extra-rounded",
        "color": "#000000",
        "gradient": null
    },
    "cornersSquareOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#000000",
            "color2": "#000000",
            "rotation": "0"
        }
    },
    "cornersDotOptions": {
        "type": "",
        "color": "#000000"
    },
    "cornersDotOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#000000",
            "color2": "#000000",
            "rotation": "0"
        }
    },
    "backgroundOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#ffffff",
            "color2": "#ffffff",
            "rotation": "0"
        }
    }
}
     );

    qrCode.append(document.getElementById("qr-link"));
    // qrCode.download({
    //     name: "qr",
    //     extension: "svg"
    // });

    $("#close-qr").on("click", function(e) {
        $("#qr-block").addClass("hide");
    });

    $("#qr-block").on("click", function(e) {
        $("#qr-info").addClass("active");
        $("#qr-block").addClass("hide");
    });
    $("#close-qr-info").on("click", function(e) {
        $("#qr-block").removeClass("hide");
        $("#qr-info").removeClass('active');
    });
    $("#copy-qr").on('click', function(e) {
          qrCode.download({
                name: url,
                extension: "jpeg"
            });


    });
</script>
<style>
    .qr-block {
        position: fixed;
        right: 10px;
        bottom: 10%;
        height: 50px;
        width: 50px;
        border-radius: 50%;
        background-color: #66abf6;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 30px;
        cursor: pointer;
        box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
        opacity: 1;
        visibility: visible;
        z-index: 100;
    }

    .qr-block.hide {
        opacity: 0;
        visibility: hidden;
    }

    .icon-close {
        position: absolute;
        font-size: 12px;
        height: 14px;
        width: 14px;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: white;
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
        top: -5px;
        right: 0;
        cursor: pointer;
    }

    .qr-info {
        opacity: 0;
        visibility: hidden;
        z-index: 100;
    }

    .qr-info.active {
        opacity: 1;
        visibility: visible;
        position: fixed;
        display: flex;
        flex-direction: column;
        height: 250px;
        width: 200px;
        top: 50%;
        right: 2%;
        transform: translateY(-50%);
        cursor: pointer;
    }

    .btn-primary {
        height: 25px;
        width: 100%;
        font-size: 14px;
        cursor: pointer;
    }
</style>

</body>

</html>