<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>chibao</h3>
                    <p>Cơ sở 1: 15 Trần Hưng Đạo, TP. Phan Thiết</p>
                    <p>Cơ sở 2: 44 Bùi Thị Xuân, TP. Phan Thiết</p>
                    <br>
                    <br>
                    <p><strong>Điện thoại</strong> <a href="tel:0983664523">0983.664.523</a> (Thầy Hải)</p>
                    <p><strong>Điện thoại</strong> <a href="tel:0983664523">0988.475.362</a> (Cô Phương)</p>
                </div>
                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Join Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    <form action="" method="post">
                    <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container d-md-flex py-4">
        <div class="me-md-auto text-center text-md-start">
          <div class="copyright mb-10">
            &copy; Copyright <strong><span>Chibao</span></strong
            >. All Rights Reserved
          </div>
          <div class="credits text-left">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
            Designed by <a href="#">TMT Team</a>
          </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>
</footer>
<div id="l-loading" style="position: fixed;z-index: 10000;top: 0;left: 0;width: 100%;height: 100%;filter: alpha(opacity=85);opacity: 1;text-align: center;display:none;">
    <div style="background-color: rgba(255, 255, 255, 0.9);width: 100%;height: 100%;">
        <img src="<?php echo $this->url->getStatic('frontend/images/waiting.gif'); ?>" alt='' title='' style="vertical-align:middle;position: relative;z-index: 10001;top: calc(50% - 16px)">
    </div>
</div>

<script src="<?php echo $this->url->getStatic('frontend/') ?>js/jquery-3.5.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/') ?>js/popper.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/') ?>js/bootstrap-4.5.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/') ?>js/bootstrap.bundle.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/lazysizes.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/ls.bgset.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/style.js?v=<?php echo time(); ?>"></script>
<script>
    const ASSETS = {};
    for (var __i = 0; __i < commands.length; __i++) {
        commands[__i]();
    }
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div id="qr-block" class="qr-block">
    <i class="fa fa-qrcode" aria-hidden="true"></i>
    <span id="close-qr" class="icon-close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </span>
</div>
<div id="qr-info" class="qr-info">
    <span id="close-qr-info" class="icon-close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </span>
    <div id="qr-link" alt="qr"></div>
    <button class="btn-primary" id="copy-qr" style="width: 200px;margin-top: -10px;">Download QR</button>
</div>
<div id="canvas"></div>
<script type="text/javascript" src="https://unpkg.com/qr-code-styling@1.5.0/lib/qr-code-styling.js"></script>

<script>
    var url = window.location.href;
    let qrCode = new QRCodeStyling(
     {
    "width": 200,
    "height": 200,
    "data": url,
    "margin": 10,
    "qrOptions": {
        "typeNumber": "0",
        "mode": "Byte",
        "errorCorrectionLevel": "Q"
    },
    "imageOptions": {
        "hideBackgroundDots": true,
        "imageSize": 0.4,
        "margin": 0
    },
    "dotsOptions": {
        "type": "extra-rounded",
        "gradient": {
            "type": "radial",
            "rotation": 0.17453292519943295,
            "colorStops": [
                {
                    "offset": 0,
                    "color": "#121112"
                },
                {
                    "offset": 1,
                    "color": "#07082c"
                }
            ]
        }
    },
    "backgroundOptions": {
        "color": "#ffffff"
    },
    "image": "<?php echo $this->url->getStatic('frontend/'); ?>/images/logo.png",
    "dotsOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#6a1a4c",
            "color2": "#6a1a4c",
            "rotation": "0"
        }
    },
    "cornersSquareOptions": {
        "type": "extra-rounded",
        "color": "#000000",
        "gradient": null
    },
    "cornersSquareOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#000000",
            "color2": "#000000",
            "rotation": "0"
        }
    },
    "cornersDotOptions": {
        "type": "",
        "color": "#000000"
    },
    "cornersDotOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#000000",
            "color2": "#000000",
            "rotation": "0"
        }
    },
    "backgroundOptionsHelper": {
        "colorType": {
            "single": true,
            "gradient": false
        },
        "gradient": {
            "linear": true,
            "radial": false,
            "color1": "#ffffff",
            "color2": "#ffffff",
            "rotation": "0"
        }
    }
}
     );

    qrCode.append(document.getElementById("qr-link"));
    // qrCode.download({
    //     name: "qr",
    //     extension: "svg"
    // });

    $("#close-qr").on("click", function(e) {
        $("#qr-block").addClass("hide");
    });

    $("#qr-block").on("click", function(e) {
        $("#qr-info").addClass("active");
        $("#qr-block").addClass("hide");
    });
    $("#close-qr-info").on("click", function(e) {
        $("#qr-block").removeClass("hide");
        $("#qr-info").removeClass('active');
    });
    $("#copy-qr").on('click', function(e) {
          qrCode.download({
                name: url,
                extension: "jpeg"
            });


    });
</script>
</body>

</html>