<?php
/**
 * @var \Learncom\Models\LearnMenu[] $menus
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'/>
    <meta name="keywords" content="<?php if(isset($meta_key)) { echo $meta_key; } ?>">
    <meta name="description" content="<?php if(isset($meta_descript)) {echo $meta_descript;} ?>">
    <?php echo $this->tag->getTitle(); ?>
    <link rel="shortcut icon" href="<?php echo $this->url->getStatic('favicon.ico?v=3'); ?>">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
    <link href="<?php echo $this->url->getStatic('frontend/css/')?>app.css?v=2" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('frontend/vendor/aos/')?>aos.css" rel="stylesheet">
    <script>
        var commands = [];
        var WEB_URL = "<?php echo $this->url->get('/'); ?>";
    </script>
</head>
<body>
<header class="header" data-spy="affix" data-offset-top="10">
    <div class="header-top">
        <img src="<?php echo isset($bannerTop) ? $bannerTop->getBannerImage() : '' ?>" alt="" title="" class="w-100">
    </div>

    <?php
    $arrClass = \Learncom\Models\LearnClass::find([
            'order' => 'class_order ASC'
    ]);
    $arrSubject = \Learncom\Models\LearnSubject::find([
            'subject_parent_id = 0',
            'order' => 'subject_order ASC'
    ]);
    $gethtml = new \Learncom\Repositories\Header();
    ?>
    <div class="header-nav">
        <div class="container">
            <div class="header-nav__wrap">
                <div class="nav-desktop-mobile flex-grow-1">
                    <div class="nav-menu-1">
                        <div class="nav-menu-wrap">
                            <?php foreach ($menus as $menu) {
                                    $type = $menu->getMenuType();
                                    $menuExcluded = '';
                                    if ($menu->getMenuExcluded()) {
                                        $menuExcluded = $menu->getMenuExcluded();
                                    }
                                ?>
                                <div class="dropdown-nav">
                                    <?php if ($menu->getMenuType() == 'home'){ ?>
                                        <span class="nav-item">
                                            <a href="<?php echo $this->url->get('/') ?>"><?php echo $menu->getMenuName() ?></a>
                                        </span>
                                    <?php } ?>
                                    <?php if ($menu->getMenuType() == 'tailieu' || $menu->getMenuType() == 'baigiang' || $menu->getMenuType() == 'khoahoc'|| $menu->getMenuType() == 'tailieuboiduong'  || $menu->getMenuType() == 'start-test' || $menu->getMenuType() == 'kiem-tra'){ ?>
                                        <span class="nav-item">
                                            <?php echo $menu->getMenuName() ?>
                                        </span>
                                        <div class="dropdown-content">
                                            <?= $gethtml->getHtmlHeader($arrClass,$arrSubject,$type,explode(',',$menuExcluded)) ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($menu->getMenuType() == 'blog'){ ?>
                                        <span class="nav-item">
                                            <a href="<?php echo $this->url->get('/blogs') ?>"><?php echo $menu->getMenuName() ?></a>
                                        </span>
                                    <?php } ?>
                                    <?php if ($menu->getMenuType() == 'login'){ ?>
                                        <?php if ($auth) { ?>
                                            <div class="dropdown-nav">
                                                <span class="nav-item" >
                                                    <img src="<?php echo $this->url->getStatic('frontend/')?>images/user-circle-solid.svg" alt="" class="icon-24 on">
                                                    <img src="<?php echo $this->url->getStatic('frontend/')?>images/user-circle-solid-white.svg" alt="" class="icon-24 off">
                                                </span>
                                                <div class="dropdown-content">
                                                    <div class="dropdown-nav">
                                                        <span class="nav-subitem">
                                                            <a href="<?php echo $this->url->get('/account/change-profile') ?>">
                                                                Thông tin tài khoản
                                                            </a>
                                                        </span>
                                                    </div>
                                                    <div class="dropdown-nav">
                                                        <span class="nav-subitem">
                                                            <a href="<?php echo $this->url->get('/logout') ?>">Thoát</a>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } else { ?>
                                            <div class="dropdown-nav">
                                                <span class="nav-item" >
                                                    <a href="<?php echo $this->url->get('/login') ?>"><?php echo $menu->getMenuName() ?></a>
                                                </span>
                                            </div>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="bar-menu-mobile btn-open-nav">
                    <div class="bar-item"></div>
                    <div class="bar-item"></div>
                    <div class="bar-item"></div>
                </div>
            </div>
        </div>
    </div>

</header>