<?php
/**
 * @var \Learncom\Models\LearnMenu[] $menus
 */
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
    <meta name="keywords" content="<?php if (isset($meta_key)) {
        echo $meta_key;
    } ?>">
    <meta name="description" content="<?php if (isset($meta_descript)) {
        echo $meta_descript;
    } ?>">
    <?php echo $this->tag->getTitle(); ?>
    <link rel="shortcut icon" href="<?php echo $this->url->getStatic('favicon.ico?v=3'); ?>">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap"
        rel="stylesheet" />
    <link href="<?php echo $this->url->getStatic('frontend/css/') ?>app.css?v=<?php echo time(); ?>" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('frontend/vendor/animate.css/') ?>animate.min.css" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('frontend/vendor/aos/') ?>aos.css" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('frontend/vendor/bootstrap-icons/') ?>bootstrap-icons.css"
        rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('frontend/vendor/boxicons/css/') ?>boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script>
        var commands = [];
        var WEB_URL = "<?php echo $this->url->get('/'); ?>";
    </script>
</head>

<body>
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center header_wrapper">
            <h1 class="logo">
                <a href="<?= $this->url->get('/'); ?>">Chi Bảo</a>
            </h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <?php
                    foreach ($menus as $menu):
                        $type = $menu['menu_type'];
                        $active_menu = "";
                        if ($type == $menu_select) {
                            $active_menu = "active";
                        }
                        $menuExcluded = [];
                        if ($menu['menu_excluded']) {
                            $menuExcluded =explode(",", $menu['menu_excluded']);

                        }
                        ?>
                        <?php if ($menu['menu_type'] == 'home'): ?>
                            <li><a class="<?= $active_menu ?>" href="<? echo $this->url->get('/') ?>">
                                    <?= $menu['menu_name'] ?>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if (in_array($menu['menu_type'], ['tailieu', 'baigiang', 'khoahoc', 'tailieuboiduong', 'start-test', 'kiem-tra'])): ?>
                            <li class="dropdown">
                                <a class="<?= $active_menu ?>" href="javascript:void(0)"><span>
                                        <?= $menu['menu_name'] ?>
                                    </span> <i class="bi bi-chevron-down"></i>
                                </a>
                                <ul>
                                    <?php
                                    $url = $type . '?classId=';
                                    foreach ($arrClass as $class):
                                        $active_class = "";
                                        if ($class['class_id'] == $class_select && $active_menu) {
                                            $active_class = "active";
                                        }
                                        ?>
                                        <li class="dropdown"><a class="<?= $active_class ?>" href="javascript:void(0)"><span>
                                                    <?= $class['class_name'] ?>
                                                </span> <i class="bi bi-chevron-right"></i></a>
                                            <ul>
                                                <?php foreach ($arrSubject as $subject):
                                                    $active_subject = "";
                                                    if (in_array($subject['subjec_id'] . "-" . $class['class_id'],$menuExcluded)) {
                                                        continue;
                                                    }
                                                    if ($subject['subject_id'] == $subject_select && $active_menu && $active_class) {
                                                        $active_subject = "active";
                                                    }
                                                    ?>
                                                    <li><a class="<?= $active_subject ?>"
                                                            href="<?= $this->url->get($url) . $class['class_id'] . '&subjectId=' . $subject['subject_id'] ?>"><?= $subject['subject_name'] ?></a></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        <?php endif ?>
                        <?php if ($menu['menu_type'] == 'blog'): ?>
                            <li><a class="<?= $active_menu ?>" href="<?php echo $this->url->get('/blogs') ?>">
                                    <?= $menu['menu_name'] ?>
                                </a>
                            </li>
                        <?php endif ?>
                    <?php endforeach; ?>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <?php if (empty($auth)): ?>
                <a href="<?php echo $this->url->get('/login') ?>" class="get-started-btn">Đăng Nhập</a>

            <?php else: ?>
                <a href="<?php echo $this->url->get('/account/change-profile') ?>" class="get-started-btn">Thông tin tài
                    khoản</a>
                <a href="<?php echo $this->url->get('/logout') ?>" class="get-started-btn">Thoát</a>

            <?php endif ?>
        </div>

    </header>