<?php
$urlPage = '?slcClass='.$school_class_id;
if (strlen($this->dispatcher->getParam("txtSearchKeyword")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearchKeyword" => $this->dispatcher->getParam("txtSearchKeyword")));
}
$slcCountry = $this->dispatcher->getParam("slcClass");
if (strlen($this->dispatcher->getParam("slcClass")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcClass" => $this->dispatcher->getParam("slcClass")));
}
if (strlen($this->dispatcher->getParam("slcSubject")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcSubject" => $this->dispatcher->getParam("slcSubject")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Học sinh</h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['message']; ?>
    </div>
<?php } ?>
<?php $message_success = isset($msg_del["success"])? $msg_del["success"] :'';
$message_error = isset($msg_del["error"])? $msg_del["error"] :'';
if(!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }if(!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-area" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearchKeyword");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-4">
                            <input maxlength="255" class="form-control" type="text" name="txtSearchKeyword" placeholder="ID, Name" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-1">
                            <h2 class="">Lớp </h2>
                        </div>
                        <div class="col-md-3">
                            <select disabled class="form-control" name="slcClass" id="slcClass">
                                <option value="">Tất cả lớp</option>
                                <?php
                                echo isset($select_school_class) ? $select_school_class : "";
                                ?>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-2 pull-right text-right">
                            <a class="btn btn-info" href="<?php echo $this->url->get("/office/create-new-student"); ?>">Add New</a>
                        </div>
                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_item->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th  class="column-title">Name </th>
                                <th  class="column-title">Ngày Đăng ký </th>
                                <th  class="column-title">Lớp học </th>
                                <th  class="column-title">Cá biệt </th>
                                <th  class="column-title">Active </th>
                                <th width="150px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php  foreach($list_item->items as $item) {
                                /**
                                 * @var \Learncom\Models\LearnUser $item
                                 */
                                ?>
                                <tr >
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?php echo $item->getUserId() ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getUserCode() ?></td>
                                    <td class=" "><?php echo $item->getUserName() ?></td>
                                    <td class=" "><?php echo $this->my->formatDateTime($item->getUserInsertTime()) ?></td>
                                    <td class=" "><?php echo \Learncom\Models\LearnSchoolClass::getNameById($item->getUserSchoolClassId())  ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getUserSpecial();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getUserActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td>
                                        <a class="btn btn-primary btn-xs margin-0"   href="<?php echo $this->url->get("/office/edit-new-student?id=".$item->getUserId()); ?> ">Chỉnh sửa</a>
                                        <a class="btn btn-primary btn-xs margin-0"   href="<?php echo $this->url->get("/dashboard/reset-student?id=".$item->getUserId())."&mode=office"; ?> ">Reset IP</a>

                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($list_item->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_item->current, $list_item->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-area]').prop('action','<?php echo $this->url->get('/office/list-new-student'); ?>');
            $('form[name=form-area]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-area]').prop('action','<?php echo $this->url->get('/office/delete-new-student'); ?>');
            $('form[name=form-area]').submit();
        });
    });
</script>