<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("txtSearchKeyword")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearchKeyword" => $this->dispatcher->getParam("txtSearchKeyword")));
}
$slcCountry = $this->dispatcher->getParam("slcClass");
if (strlen($this->dispatcher->getParam("slcClass")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcClass" => $this->dispatcher->getParam("slcClass")));
}
if (strlen($this->dispatcher->getParam("slcSubject")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcSubject" => $this->dispatcher->getParam("slcSubject")));
}
$chapter_id = strlen($this->dispatcher->getParam("slcChapter"));
if (strlen($this->dispatcher->getParam("slcChapter")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcChapter" => $this->dispatcher->getParam("slcChapter")));
}
?>
<script>
    $(document).ready(function(){
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('dashboard/delete-exam-lesson');?>";
                var id= $("#document-id").val();
            str=str.concat("?id=").concat(id);
            $('#delete').attr("href",str);
        });
        $('button[name=search]').click(function () {
            $('form[name=read_form]').prop('action', '<?php echo $this->url->get('/dashboard/list-exam-lesson'); ?>');
            $('form[name=read_form]').submit();
        });
        $('.class-subject').on('change',function () {
            var subject_id = $('#slcSubject').val();
            var exam_subject_id = '<?= $this->dispatcher->getParam("slcSubject") ? $this->dispatcher->getParam("slcSubject") : 0 ?>';
            $.ajax({
                url: "<?php echo $this->url->get("/dashboard/get-exam-subject")?>",
                async: false,
                type: "POST",
                dataType: "JSON",
                data: {'subject_id': subject_id,
                    'exam_subject_id' : exam_subject_id
                },
                success: function(data){
                    $('#slcExamSubject').html('<option value="">Tất cả Chuyên đề</option>'+data.html);
                    $('#slcSubject').val(data.subject_id);
                }
            });
        }).trigger('change');
        $('#slcExamSubject').on('change',function () {
            var subject_id = $('#slcSubject').val();
            var class_id = $('#slcClass').val();
            var exam_subject_id = $('#slcExamSubject').val();
            var chapter_id ='<?= $this->dispatcher->getParam("slcChapter") ? $this->dispatcher->getParam("slcChapter") : 0 ?>';
            $.ajax({
                url: "<?php echo $this->url->get("/dashboard/get-exam-chapter")?>",
                async: false,
                type: "POST",
                dataType: "JSON",
                data: {'subject_id': subject_id,
                    'exam_subject_id' : exam_subject_id,
                    'chapter_id' : chapter_id,
                    'class_id' : class_id
                },
                success: function(data){
                    $('#slcChapter').html('<option value="">Chọn Chương</option>'+data.html);
                }
            });
        }).trigger('change');
    });
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-exam-lesson");?>'>  Tài Liệu </a></li>");
</script>

<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form" id="read_form"  >
    <div>
        <table>
            <?php
            $keyword=$this->dispatcher->getParam("key_word");
            ?>

            <tr>
                <th>
                    <select  id="slcClass" name="slcClass" class="class-subject">
                        <option value="">Tất cả lớp học</option>
                        <?php echo isset($select_class) ? $select_class : ""?>
                    </select><th>
                <th>
                <th>
                    <select  id="slcSubject" name="slcSubject" class="class-subject">
                        <option value="">Tất cả môn học</option>
                        <?php echo isset($select_subject) ? $select_subject : ""?>
                    </select><th>
                <th>
                <th>
                    <button type="button" name="search" id="search" value="Search" class="btn btn-primary">Search</button>
                </th>
                <th><a href="<?php echo $this->url->get('dashboard/create-exam-lesson')?>" name="create_article" id="create_article" class="btn btn-primary"/>Add New</th></th>
            </tr>
        </table>
        <table>
            <tr>
                <th>
                    <select  id="slcExamSubject" name="slcExamSubject" class="">
                    </select><th>
                <th>
                <th>
                    <select  id="slcChapter" name="slcChapter" >
                    </select>
                <th>
            </tr>
        </table>
    </div>
    <div class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center;width: 50px">ID</th>
                <th style="text-align:center;width: 300px">Name</th>
                <th style="text-align:center;">Lớp</th>
                <th style="text-align:center;">Chương</th>
                <th style="text-align:center;width: 50px">Số câu hỏi</th>
                <th style="text-align:center;width: 50px">order</th>
                <th style="text-align:center;width: 50px">Active</th>
                <th style="text-align:center;width: 300px">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php

            foreach($list_item->items as $item){
                $arrGroup = \Learncom\Repositories\ExamGroup::findByExamLesson($item->getLessonId());
                $number_q = 0;
                foreach ($arrGroup as $group) {
                    $arrQ = explode(',',$group->getGroupDataTest());
                    $number_q += count($arrQ);
                }
                ?>
                <script>
                    $(function(){
                        $('#delete<?= $item->getLessonId()?>').live("click",function(e){
                            e.preventDefault();
                            $('#warn').modal('show');
                            var id=$("#<?= $item->getLessonId();?>").text();
                            $("#document-id").val(id);
                            var str="Are you sure to remove lớp học ID = ".concat(id);
                            $("#message").text(str);

                        });
                    });
                </script>
                <tr>
                    <td style="text-align:center;" class="center" id="<?php echo $item->getLessonId(); ?>"><?php echo $item->getLessonId(); ?></td>
                    <td  style="text-align:left;" class="center">
                        <?php echo $item->getLessonName(); ?>
                    </td>
                    <td  style="text-align:left;" class="center">
                        <?php echo \Learncom\Repositories\ClassSubject::getNameClassByIds($item->getLessonClassId()) ?>
                    </td>
                    <td  style="text-align:left;" class="center">
                        <?php echo \Learncom\Repositories\ExamChapter::getNameById($item->getLessonChapterId()); ?>
                    </td>
                    <td  style="text-align:left;">
                        <?= $number_q ?>
                    </td>
                    <td  style="text-align:left;">
                        <?php echo $item->getLessonOrder(); ?>
                    </td>
                    <td style="text-align:left;" class="center">
                        <?php
                        $status = $item->getLessonActive();
                        $classStatus = ($status == "Y") ? "success" : "info";
                        ?>
                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                    </td>


                    <td  style="text-align:center;"class="center">
                        <a id="edit_account" class="btn btn-success" href="<?php echo $this->url->get('/dashboard/create-exam?slcLesson=');?><?php echo $item->getLessonId()."&lock=true"; ?>">
                            <i class="icon-edit icon-white"></i>
                            Thêm Câu hỏi
                        </a>
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('dashboard/edit-exam-lesson');?>?id=<?php echo $item->getLessonId(); ?>">
                            <i class="icon-edit icon-white"></i>
                            Chỉnh
                        </a>
                        <a id="delete<?php echo $item->getLessonId();?>" class="btn btn-danger" href="">delelte</a>
                    </td>
                </tr>
            <?php }?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-6 ">
                <div style="float:left">
                    <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?= $list_item->total_items;?></strong> Tài liệu</p>

                </div>
            </div>
            <div class="col-md-6 t pull-right">
                <?php if ($list_item->total_pages > 1) { ?>
                    <nav class="pagination pagination-centered">
                        <?php if ($urlPage != "?") $urlPage .= "&";
                        $urlPage .= "page=";
                        echo $this->my->renderPagination($urlPage, $list_item->current, $list_item->total_pages, 2);
                        ?>
                    </nav>
                <?php } ?>
            </div>
        </div>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="document-id" name="document-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>