<?php
/**
 * @var $auth;
 * @var $parent_keyword;
 * @var $type;
 * @var $class_id;
 * @var $subject_id;
 * @var \Learncom\Models\LearnVideo[] $lessons
 * @var \Learncom\Models\LearnVideo[] $listLessons
 * @var \Learncom\Models\LearnGroup[] $listChapters
 */

?>
<main class="videoCourse_wrapper">
    <div class="videoCourse_top">
        <a href="/" title="home" class="videoCourse_back"><i class="bx bx-chevron-left"></i>Home</a>
        <h1 class="videoCourse_title">
            <?= $title_name ?>
        </h1>
    </div>
    <div class="videoCourse_content">
        <div class="videoCourse_video">
            <?php if (strpos($link, "vimeo") || strpos($link, "video") || strpos($link, "youtube")): ?>
                <iframe src="<?= $link ?>" allowfullscreen></iframe>
            <?php else: ?>
                <iframe src="<?= $link ?>" type="application/pdf" height="100%" width="100%"></iframe>
            <?php endif ?>
        </div>
        <div class="videoCourse_rightSidebar">
            <div class="videoCourse_rightSidebar-top">
                <h2>Nội dung bài học</h2>
            </div>
            <div class="videoCourse_collapsibleContent">
                <?php foreach ($chapters as $chapter):
                    ?>
                    <a class="videoCourse_collapsible <?= $chapter['active'] ?> <?= $chapter['active'] ? "" : "collapseed" ?> "
                        data-toggle="collapse" href="#chapter_<?= $chapter['id'] ?>" role="button"
                        aria-expanded="<?= $chapter['active'] ? true : false ?> "
                        aria-controls="chapter_<?= $chapter['id'] ?>">
                        <?= $chapter['name'] ?> <i class='bx bxs-chevron-down'></i>
                    </a>
                    <div class="collapse <?= $chapter['active'] ? "show" : "" ?>" id="chapter_<?= $chapter['id'] ?>"
                        class="videoCourse_contentRight">
                        <?php foreach ($lessons[$chapter['id']] as $lesson):
                            ?>
                            <div class="contentRight-item <?= $lesson['active'] ?>">
                                <a href="<?= $lesson['href'] ?>">
                                    <?= $lesson['name'] ?>
                                </a>
                            </div>

                        <?php endforeach ?>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <div class="modal-shadow"></div>
    <div class="modal-video" id="myModal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-custom">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thông báo</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Bạn đang xem đến:
                        <b><?= $name ?? "" ?></b>
                    </p>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <button id='close_wa' type="button" class="btn btn-primary" data-dismiss="modal">Tiếp
                        tục</button>
                </div>
            </div>
        </div>
    </div>

</main>

<script type="text/javascript">
    commands.push(function () {
        <?php if ($is_continue): ?>
            $("#myModal").show();
            $("#close_wa").on('click', function () {
                closeModal();
            });
            // Function to close the modal
            function closeModal() {
                var modal = document.getElementById('myModal');
                var backdrop = document.querySelector('.modal-shadow');

                modal.style.display = 'none';
                backdrop.style.display = 'none';
            }
        <?php endif ?>

    })
</script>
<style>
    /* Modal Styling */
    .modal-video {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 1050;
        /* Higher value to ensure it displays on top of other elements */
    }

    /* Overlay Styling */
    .modal-shadow.show {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: 1040;
        /* Lower value than modal to ensure it's behind the modal */
        background-color: rgba(0, 0, 0, 0.5);
        /* Semi-transparent black background */
    }

    .modal-footer .btn {
        width: 100px;
        margin-left: 5px;
        margin-right: 5px;
    }

    .modal-title {
        text-align: center;
        font-size: 20px;
    }
</style>