<?php
/**
 * @var $auth;
 * @var $parent_keyword;
 * @var $type;
 * @var $class_id;
 * @var $subject_id;
 * @var \Learncom\Models\LearnVideo[] $lessons
 * @var \Learncom\Models\LearnVideo[] $listLessons
 * @var \Learncom\Models\LearnGroup[] $listChapters
 */
?>
<main>
    <div class="container-fluid">
        <h2 class="text-main text-center text-bolder my-20">
            <?php echo \Learncom\Repositories\ClassSubject::findFirstSubjectNameById($subject_id) . ' ' . \Learncom\Repositories\ClassSubject::findFirstClassNameById($class_id) ?>
        </h2>
        <?php
        if (count($lessons) > 0) {
            if ($group_id == 0) {
                $group_id = $lessons[0]->getVideoGroupId();
            }
        ?>
            <div class="row mx-0 list-courses-wrap">
                <div class="col-12 col-lg-4 col-xl-3 list-coutses">
                    <div class="list-wrap box-shadow-1">
                        <?php

                        if (sizeof($listChapters) > 0) {
                            $lesson_link = "";
                            foreach ($listChapters as $chapter) {
                                if (!in_array($chapter->getGroupId(), $auth['group_excluded_ids'])) {
                                    $aria_expanded = "";
                                    $is_show = '';
                                    if ($chapter->getGroupId() == $group_id) {
                                        $aria_expanded = 'aria-expanded="true"';
                                        $is_show = "show";
                                    }

                        ?>
                                    <span id="tab1-<?php echo $chapter->getGroupId() ?>" class="item-style item-menu justify-content-start" data-toggle="collapse" data-target="#course-sub-<?php echo $chapter->getGroupId() ?>" <?= $aria_expanded ?>>
                                        <?php echo $chapter->getGroupName() ?>
                                    </span>
                                    <?php
                                    $listLessons = \Learncom\Repositories\Video::findByClassAndSubjectAndTypeAndGroup($class_id, $subject_id, $type, $chapter->getGroupId());
                                    if (sizeof($listLessons) > 0) {
                                    ?>
                                        <div class="collapse <?= $is_show ?>" id="course-sub-<?php echo $chapter->getGroupId() ?>">
                                            <div class="sub-list">
                                                <?php foreach ($listLessons as $lesson) {
                                                    if ($video_id == 0) {
                                                        $video_id = $lessons[0]->video_id;
                                                    }
                                                    $class_style = "";
                                                    if ($lesson->video_id == $video_id) {
                                                        $lesson_link = $lesson->video_link;
                                                        $class_style = "active";
                                                    }
                                                    $href_a = $base_url . "&groupId=" . $chapter->group_id . "&videoId=" .  $lesson->video_id;
                                                ?>
                                                    <a id="<?= $chapter->group_id ?>-<?= $lesson->video_id ?>" href="<?= $href_a ?>" class="item-style <?= $class_style ?> justify-content-start" data-src-iframe="<?php echo $lesson->video_link ?>">
                                                        <?php echo $lesson->video_name ?>
                                                    </a>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    <?php } ?>
                        <?php }
                            }
                        } ?>
                    </div>
                </div>
                <div class="col-12 col-lg-8 col-xl-9 courses-detail">
                    <div class="video-iframe">
                        <iframe src="<?= $lesson_link ?>" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        <?php } ?>

    </div>
</main>

<script type="text/javascript">
    commands.push(function() {
        // var link = window.location.href;
        // var href = link.split('#')[1];
        // var group_id = href.split('-')[0];
        // var video_id = href.split('-')[1];
        // $("#tab1-" + group_id).click();
        // $("#" + href).click();
        // $src = "<?= $lesson_link ?>";
        // try {
        //     $(".courses-detail iframe").attr("src", src);
        // } catch (err) {
        //     console.log(err);
        // }

        $(function() {
            $(".collapse").on("click", function(e) {
                e.stopPropagation();
            });
            // $(".item-style:not(.item-menu)").on("click", function(e) {
            //     $(".item-style.active").removeClass("active");
            //     let parent = this.parentElement;
            //     let src = "";
            //     $(parent).find(".item-menu[aria-expanded='true']").click();
            //     $(this).addClass("active");
            //     src = this.dataset.srcIframe;
            //     if (!src) return;
            //     try {
            //         $(".courses-detail iframe").attr("src", src);
            //     } catch (err) {
            //         console.log(err);
            //     }
            // });
            $(".item-menu").on("click", function(e) {
                $(".item-menu").each((ind, ele) => {
                    if (ele !== this) {
                        let target = $(ele).data("target");
                        $(target).collapse("hide");
                    }
                });
                let parent = this.parentElement;
                $(parent).children(".item-style.active").removeClass('active');
            })
        });
    })
</script>