<?php
/**
 * @var $parent_keyword;
 * @var $type;
 * @var $class_id;
 * @var $subject_id;
 * @var \Learncom\Models\LearnDocument[] $documents
 * @var \Learncom\Models\LearnDocument[] $listDocuments
 * @var \Learncom\Models\LearnChapter[] $chapters
 */
$subject_parents_id = 0;
$subject = \Learncom\Repositories\ClassSubject::findFirstBySubjectId($subject_id);
if ($subject){
    $subject_parents_id = $subject->getSubjectParentId();
}
?>
<main>
    <div class="container-fluid">
        <h2 class="text-main text-center text-bolder my-20">
            <?php echo \Learncom\Repositories\ClassSubject::findFirstSubjectNameById($subject_id).' '. \Learncom\Repositories\ClassSubject::findFirstClassNameById($class_id)?>
        </h2>
        <?php
        $first_document = new \Learncom\Models\LearnDocument();
        ?>
        <div class="row mx-0 list-courses-wrap">
            <div class="col-12 col-lg-2 list-coutses">
                <div class="list-wrap box-shadow-1">
                    <?php
                    if ($subject_parents_id != 0){
                        $chapters = \Learncom\Repositories\Chapter::findByClassAndSubject($class_id,$subject_parents_id);
                    } else {
                        $chapters = \Learncom\Repositories\Chapter::findByClassAndSubject($class_id,$subject_id);
                    }
                    if (sizeof($chapters) > 0){
                        foreach ($chapters as $chapter){
                            $id = $chapter->getChapterId();
                            ?>
                            <div class="group_chapter_<?=$id?>">
                                <span class="item-style item-menu justify-content-start " data-toggle="collapse" data-target="#course-sub-<?php echo $chapter->getChapterId() ?>" <?php echo ($chapter->getChapterId() == $first_document->document_chapter_id) ? 'aria-expanded="true"' : '' ?>>
                                    <?php echo $chapter->getChapterName() ?>
                                </span>
                                <?php
                                $listDocuments = [];
                                if (count($group_subject_id) > 0) {
                                    foreach ($group_subject_id as $group_id) {
                                        $listDocumentsTemp = \Learncom\Repositories\Document::findByClassAndSubjectAndChapterAndGroup($class_id,$subject_id,$chapter->getChapterId(),$group_id,'excellent');
                                        foreach ($listDocumentsTemp as $temp) {
                                            if ($first_document->document_id == null) {
                                                $first_document = $temp;
                                            }
                                            array_push($listDocuments,json_encode($temp));
                                        }
                                    }
                                    $listDocuments = array_unique($listDocuments);
                                } else {
                                    $listDocuments = \Learncom\Repositories\Document::findByClassAndSubjectAndChapter($class_id,$subject_id,$chapter->getChapterId());
                                }
                                if (sizeof($listDocuments) > 0){
                                    ?>
                                    <div class="collapse<?php echo ($chapter->getChapterId() == $first_document->document_chapter_id) ? ' show' : '' ?>" id="course-sub-<?php echo $chapter->getChapterId() ?>">
                                        <div class="sub-list">
                                            <?php foreach ($listDocuments as $lesson){
                                                if (is_string($lesson)) {
                                                    $lesson = json_decode($lesson);
                                                }
                                                /**
                                                 * @var \Learncom\Models\LearnDocument $lesson;
                                                 * @var \Learncom\Models\LearnDocument $first_document;
                                                 */
                                                ?>
                                                <span class="item-style<?php echo ($lesson->document_id == $first_document->document_id) ? ' active' : '' ?> justify-content-start" data-src-iframe="<?php echo $lesson->document_link ?>" data-public="<?php echo $lesson->document_is_public ?>">
                                                <?php echo $lesson->document_name ?>
                                            </span>
                                            <?php } ?>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                            <script type="text/javascript">
                                commands.push(function () {
                                    var count = "<?= count($listDocuments) ?>";
                                    console.log(parseInt(count));
                                    var id = '<?=$id ?>';
                                    if (parseInt(count) == 0) {
                                        $('.group_chapter_' + id).addClass('d-none');
                                    }
                                });
                            </script>
                        <?php }} ?>
                </div>
            </div>
            <div class="col-12 col-lg-10 courses-detail">
                <div class="video-iframe">
                    <iframe src="<?php echo $first_document->document_link ?>" <?php echo $first_document->document_is_public == "N" ? 'sandbox="allow-top-navigation-by-user-activation allow-orientation-lock allow-modals allow-pointer-lock allow-presentation allow-same-origin allow-forms allow-top-navigation allow-scripts"' : '' ?>></iframe>
                </div>
            </div>
        </div>

    </div>
</main>

<script type="text/javascript">
    commands.push(function () {
        $(function() {
            $(".collapse").on("click", function(e){
                e.stopPropagation();
            });
            $(".item-style:not(.item-menu)").on("click", function(e){
                $(".item-style.active").removeClass("active");
                let parent = this.parentElement;
                let src, publicDoc, sandbox;
                $(parent).find(".item-menu[aria-expanded='true']").click();
                $(this).addClass("active");
                src = this.dataset.srcIframe;
                publicDoc = this.dataset.public;
                if (publicDoc === "N"){
                    $(".courses-detail iframe").attr("sandbox","allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-same-origin allow-scripts allow-top-navigation allow-top-navigation-by-user-activation");
                } else {
                    $(".courses-detail iframe").removeAttr("sandbox");
                }
                if(!src) return;
                $(".courses-detail iframe").attr("src", src);
            });
            $(".item-menu").on("click", function(e){
                $(".item-menu").each((ind, ele) => {
                    if(ele !== this) {
                    let target = $(ele).data("target");
                    $(target).collapse("hide");
                }
            });
                let parent = this.parentElement;
                $(parent).children(".item-style.active").removeClass('active');
            })
        });
    })
</script>