<?php

/**
 * @var $parent_keyword;
 * @var \Learncom\Models\LearnTypeDgnl[] $arType
 */
?>

<main data-aos="fade-in" style="background-color: #fafafa">
    <div class="infoCourse_top">
        <div class="container">
            <h2>Đánh Giá Năng Lực</h2>
        </div>
    </div>
    <section class="section container infoCourse_wrapper">

        <div id="courses" class="courses row section-slick" data-aos="zoom-in" data-aos-delay="100">
            <?php foreach ($arType as $type): ?>

                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                    <a href="<?= $this->url->get("/dgnl/" . $type['type_id']) ?>">
                        <div class="course-item">
                            <div class="course-img">
                                <img src="<?= $type['type_image'] ?>">
                            </div>
                            <div class="course-content">
                                <div class="d-flex justify-content-between align-items-center mb-3 course-label">
                                    <h4>
                                        <?= $type['type_name'] ?>
                                    </h4>
                                </div>
                                <h3 class="course-title">
                                    <a href="<?= $this->url->get("/dgnl/" . $type['type_id']) ?>">
                                        <?= $type['type_descriptiont'] ?>
                                    </a>
                                </h3>
                                <p class="course-text">
                                    <?= $type['type_content'] ?>
                                </p>
                                <div class="trainer d-flex justify-content-between align-items-center">
                                    <div class="trainer-profile d-flex align-items-center">
                                        <img src=" <?= $type['type_icon'] ?>" class="img-fluid" alt="">
                                        <span>
                                            <?= $type['type_teacher'] ?>
                                        </span>
                                    </div>
                                    <div class=" d-flex align-items-center">
                                        <i class='bx bxs-calendar'></i>
                                        <span>
                                            <?= $type['total_video'] ?> bài giảng/video
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

            <?php endforeach ?>
        </div>
    </section>

</main>