<?php

/**
 * @var $parent_keyword;
 * @var \Learncom\Models\LearnTypeDgnl[] $arType
 */
?>

<main data-aos="fade-in">
    <div class="infoCourse_top">
        <div class="container">
            <h2>Đánh giá năng lực </h2>
        </div>
    </div>
    <section class="container infoCourse_wrapper" data-aos="fade-up">
        <div class="row" data-aos="zoom-in" data-aos-delay="100">
            <?php foreach ($arType as $type) :
            ?>
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-lg-0">
                    <div class="course-item">
                        <img src="<?= $type['type_icon'] ?>" class="img-fluid" alt="...">
                        <div class="course-content">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4><?= $type['type_name'] ?></h4>
                                <p class="price">$180</p>
                            </div>
                            <h3><a href="<?= $this->url->get("/dgnl/" . $type['type_id']) ?>"><?= $type['type_name'] ?></a></h3>
                            <p><?= $type['type_descriptiont'] ?></p>
                            <div class="trainer d-flex justify-content-between align-items-center">
                                <div class="trainer-profile d-flex align-items-center">
                                    <img src="<?= $type['type_image'] ?>" class="img-fluid" alt="">
                                    <span><?= $type['type_teacher'] ?></span>
                                </div>
                           
                            </div>
                        </div>
                    </div>
                </div> <!-- End Course Item-->
            <?php endforeach ?>
        </div>
    </section>

</main>