<?php
$urlPage = "?id=".$id;

?>
<script>
    $(document).ready(function(){
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('dashboard/delete-exam');?>";
            var id= $("#document-id").val();
            str=str.concat("?id=").concat(id);
            $('#delete').attr("href",str);
        });
        $('button[name=search]').click(function () {
            $('form[name=read_form]').prop('action', '<?php echo $this->url->get('/dashboard/list-exam'); ?>');
            $('form[name=read_form]').submit();
        });
        $('#create_article').on('click',function () {
            history.back()
        })

    });
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-document");?>'>  Tài Liệu </a></li>");
</script>

<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form" id="read_form"  >
    <a href="" name="create_article" id="create_article" class="btn btn-primary pull-left">Back</a>
    <div class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center;">Số</th>
                <th style="text-align:center;">Câu hỏi</th>
                <th style="text-align:center;width: 30%">Lời Giải</th>
                <th style="text-align:center;">Đáp Án</th>
                <th style="text-align:center;width: 200px">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php


            foreach($list_item->items as $item){
                ?>
                <script>
                    $(function(){
                        $('#delete<?= $item->getFolderId()?>').live("click",function(e){
                            e.preventDefault();
                            $('#warn').modal('show');
                            var id=$("#<?= $item->getFolderId()?>").attr('data-browse');
                            $("#document-id").val(id);
                            var str="Bạn có muốn xóa Câu hỏi ID = ".concat(id);
                            $("#message").text(str);

                        });
                    });
                </script>
                <tr>

                    <td  style="text-align:center;"class="center">
                       <?= $item->getFolderStatus() ?>
                    </td>
                    <td style="text-align:center;" class="center" id="<?php echo  $item->getFolderId(); ?>" data-browse="<?php echo  $item->getFolderId(); ?>">
                        <?php if(file_exists(__DIR__."/../../../..".$item->getFolderLink()) && $item->getFolderLink()!="" && $item->getFolderLink()!=null) {?>
                        <img style="width: 500px;height: 100px" src="<?=$this->url->getStatic($item->getFolderLink());?>" title="<?php echo "câu hỏi". $item->getFolderId(); ?>" alt="<?php echo "câu hỏi". $item->getFolderId(); ?>">
                        <?php }?>
                    </td>
                    <td style="text-align:center;" class="center" id="answer<?php echo  $item->getFolderId(); ?>">
                        <?php if (file_exists(__DIR__."/../../../..".$item->getFolderLinkComment()) && $item->getFolderLinkComment()!="" && $item->getFolderLinkComment()!=null) { ?>
                            <img style="width: 500px;height: 100px" src="<?=$this->url->getStatic($item->getFolderLinkComment()); ?>" title="<?php echo "đáp án". $item->getFolderId(); ?>" alt="<?php echo "đáp án". $item->getFolderId(); ?>">
                        <?php } ?>
                    </td>
                    <td style="text-align:center;" class="center" >
                    <?php if (isset($arrAnserwer[$item->getFolderStatus()])) {
                        echo $arrAnserwer[$item->getFolderStatus()];
                    } ?>
                    </td>

                    <td  style="text-align:center;"class="center">
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('/dashboard/edit-detail-test');?>?id=<?php echo $item->getFolderId(); ?>&testId=<?= $id?>">
                            <i class="icon-edit icon-white"></i>
                            Chính sửa
                        </a>
                        <a id="delete<?= $item->getFolderId()?>" class="btn btn-danger" href="">delelte</a>
                    </td>

                </tr>
            <?php }?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-6 ">
                <div style="float:left">
                    <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?= $list_item->total_items;?></strong> Câu hỏi</p>

                </div>
            </div>
            <div class="col-md-6 t pull-right">
                <?php if ($list_item->total_pages > 1) { ?>
                    <nav class="pagination pagination-centered">
                        <?php if ($urlPage != "?") $urlPage .= "&";
                        $urlPage .= "page=";
                        echo $this->my->renderPagination($urlPage, $list_item->current, $list_item->total_pages, 2);
                        ?>
                    </nav>
                <?php } ?>
            </div>
        </div>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="document-id" name="document-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>