<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("txtSearchKeyword")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearchKeyword" => $this->dispatcher->getParam("txtSearchKeyword")));
}
$slcCountry = $this->dispatcher->getParam("slcClass");
if (strlen($this->dispatcher->getParam("slcClass")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcClass" => $this->dispatcher->getParam("slcClass")));
}
if (strlen($this->dispatcher->getParam("slcSubject")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcSubject" => $this->dispatcher->getParam("slcSubject")));
}
$chapter_id = strlen($this->dispatcher->getParam("slcChapter"));
if (strlen($this->dispatcher->getParam("slcChapter")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcChapter" => $this->dispatcher->getParam("slcChapter")));
}
?>
<script>
    $(document).ready(function(){
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('dashboard/delete-test');?>";
                var id= $("#document-id").val();
            str=str.concat("?id=").concat(id);
            $('#delete').attr("href",str);
        });
        $('button[name=search]').click(function () {
            $('form[name=read_form]').prop('action', '<?php echo $this->url->get('/dashboard/list-test'); ?>');
            $('form[name=read_form]').submit();
        });


    });
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-test");?>'>  Đề thi</a></li>");
</script>

<?php if(isset($msg_result['status']))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form" id="read_form"  >
    <div>
        <table>
            <?php
            $keyword=$this->dispatcher->getParam("key_word");
            ?>

            <tr>
                <th><input  placeholder="Keyword(Name)" value="<?= isset($keyword) ? $keyword : ""; ?>" name="txtSearchKeyword" id="txtSearchKeyword" type="text"/></th>
                <th>
                    <select  id="slcClass" name="slcClass" class="class-subject">
                        <option value="">Tất cả lớp học</option>
                        <?php echo isset($select_class) ? $select_class : ""?>
                    </select><th>
                <th>
                <th>
                    <select  id="slcSubject" name="slcSubject" class="class-subject">
                        <option value="">Tất cả môn học</option>
                        <?php echo isset($select_subject) ? $select_subject : ""?>
                    </select><th>
                <th>

                <th>
                    <button type="button" name="search" id="search" value="Search" class="btn btn-primary">Search</button>
                </th>
                <th><a href="<?php echo $this->url->get('dashboard/create-test')?>" name="create_article" id="create_article" class="btn btn-primary"/>Add New</th></th>
            </tr>
        </table>
    </div>
    <div class="box-content">
        <h4>Note: Khi xóa đề thì thì tất cả bài làm của học sinh sẽ bị xóa</h4>
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center;width: 300px">Tên</th>
                <th style="text-align:center;">Lớp</th>
                <th style="text-align:center;">Khóa</th>
                <th style="text-align:center;width: 100px">Số Lần Thi</th>
                <th style="text-align:center;width: 100px">Xem Điểm Thi</th>
                <th style="text-align:center;width:100px">Xem đáp án</th>
                <th style="text-align:center;width: 50px">Active</th>
                <th style="text-align:center;width: 50px">order</th>
                <th style="text-align:center;width: 300px">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php

            foreach($list_item->items as $item){
                /**
                 * @var \Learncom\Models\LearnTest $item
                 */
                ?>
                <script>
                    $(function(){
                        $('#delete<?= $item->getTestId()?>').live("click",function(e){
                            e.preventDefault();
                            $('#warn').modal('show');
                            var id=$("#<?= $item->getTestId();?>").attr('data-browse');
                            $("#document-id").val(id);
                            var str="Are you sure to remove lớp học ID = ".concat(id);
                            $("#message").text(str);

                        });
                    });
                </script>
                <tr>
                    <td  style="text-align:left;" class="center" id="<?php echo $item->getTestId(); ?>" data-browse="<?php echo $item->getTestId(); ?>">
                        <?php echo $item->getTestName(); ?>
                    </td>
                    <td  style="text-align:left;" class="center">
                        <?php echo \Learncom\Repositories\ClassSubject::getNameByClassAndSubject($item->getTestClassId(),$item->getTestSubjectId()) ?>
                    </td>
                    <td  style="text-align:left;" class="center">
                        <?php echo \Learncom\Repositories\Chapter::getNameById($item->getTestGroupId()); ?>
                    </td>
                    <td style="text-align:left;" class="center">
                        <?php
                        $how = $item->getTestOnlyOne();
                        $classhow  = ($how == "Y") ? "success" : "info";
                        $how_test = $how == "Y" ? "Một lần" : "Không giới hạn";
                        ?>
                        <span class="label label-<?php echo $classhow; ?>"><?php echo $how_test; ?></span>
                    </td>
                    <td style="text-align:left;" class="center">
                        <?php
                        $score = $item->getTestPublicScore();
                        $classScore  = ($score == "Y") ? "success" : "info";
                        ?>
                        <span class="label label-<?php echo $classScore; ?>"><?php echo $score; ?></span>
                    </td>
                    <td style="text-align:left;" class="center">
                        <?php
                        $answer = $item->getTestIsPublicAnswer();
                        $classAnswer = ($answer == "Y") ? "success" : "info";
                        ?>
                        <span class="label label-<?php echo $classAnswer; ?>"><?php echo $answer; ?></span>
                    </td>
                    <td style="text-align:left;" class="center">
                        <?php
                        $status = $item->getTestActive();
                        $classStatus = ($status == "Y") ? "success" : "info";
                        ?>
                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                    </td>
                    <td  style="text-align:left;">
                        <?php echo $item->getTestOrder(); ?>
                    </td>

                    <td  style="text-align:center;"class="center">
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('/dashboard/detail-test-exam');?>?id=<?php echo $item->getTestId(); ?>">
                            <i class="icon-edit icon-white"></i>
                            Xem
                        </a>
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('dashboard/edit-test');?>?id=<?php echo $item->getTestId(); ?>">
                            <i class="icon-edit icon-white"></i>
                            Chính sửa
                        </a>
                        <a id="delete<?php echo $item->getTestId();?>" class="btn btn-danger" href="">delelte</a>
                    </td>

                </tr>
            <?php }?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-6 ">
                <div style="float:left">
                    <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?= $list_item->total_items;?></strong> Đề Thi</p>

                </div>
            </div>
            <div class="col-md-6 t pull-right">
                <?php if ($list_item->total_pages > 1) { ?>
                    <nav class="pagination pagination-centered">
                        <?php if ($urlPage != "?") $urlPage .= "&";
                        $urlPage .= "page=";
                        echo $this->my->renderPagination($urlPage, $list_item->current, $list_item->total_pages, 2);
                        ?>
                    </nav>
                <?php } ?>
            </div>
        </div>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input  type="hidden" id="document-id" name="document-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>