</div><!--/fluid-row-->

<hr>

<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Warning !</h3>
    </div>
    <div class="modal-body">
        <p>Are you sure to delete for that !</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <a href="#" class="btn btn-primary">Yes</a>
    </div>
</div>

<footer>

</footer>

</div><!--/.fluid-container-->

<!-- external javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="<?php echo $this->url->getStatic("backend/js/select2/select2.min.js"); ?>"></script>
<!-- jQuery UI -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery-ui-1.8.21.custom.min.js"></script>
<!-- transition / effect library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-transition.js"></script>
<!-- alert enhancer library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-alert.js"></script>
<!-- modal / dialog library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-modal.js"></script>
<!-- custom dropdown library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-dropdown.js"></script>
<!-- scrolspy library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-scrollspy.js"></script>
<!-- library for creating tabs -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-tab.js"></script>
<!-- library for advanced tooltip -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-tooltip.js"></script>
<!-- popover effect library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-popover.js"></script>
<!-- button enhancer library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-button.js"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-collapse.js"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-carousel.js"></script>
<!-- autocomplete library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-typeahead.js"></script>
<!-- tour library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-tour.js"></script>
<!-- library for cookie management -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.cookie.js"></script>
<!-- calander plugin -->
<script src='<?php echo $this->url->getStatic('backend/template/'); ?>js/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.dataTables.min.js'></script>

<!-- chart libraries start -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/excanvas.js"></script>
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.flot.min.js"></script>
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.flot.pie.min.js"></script>
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.flot.stack.js"></script>
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.flot.resize.min.js"></script>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.chosen.min.js"></script>
<!-- checkbox, radio, and file input styler -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.uniform.min.js"></script>
<!-- plugin for gallery image view -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.colorbox.min.js"></script>
<!-- rich text editor library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.cleditor.min.js"></script>
<!-- notification plugin -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.noty.js"></script>
<!-- file manager library -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.elfinder.min.js"></script>
<!-- star rating plugin -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/jquery.history.js"></script>
<!-- application script for Charisma demo -->
<!--<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/charisma.js"></script>-->
<!-- datetimepicker -->
<!--<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap.min.js"></script>-->


<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-datetimepicker.js"></script>
<script src="<?php echo $this->url->getStatic('backend/template/'); ?>js/bootstrap-datetimepicker.fr.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
    $('.form_datetime').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
    $('.form_date').datetimepicker({
        format: "dd-mm-yyyy",
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        forceParse: 0
    });
    $('.form_time').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 1,
        minView: 0,
        maxView: 1,
        forceParse: 0
    });
</script>
</body>
</html>