
<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form" id="read_form"  >
    <div class="box-content">
        <h3>Các Bài Kiểm Tra Của: <?= $name ?></h3>
        <a name="create_article" id="create_article" class="btn btn-primary pull-lefy">Back</a>
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center; width: 30%">Tên Bài thi</th>
                <th style="text-align:center; width: 10%">Lớp </th>
                <th style="text-align:center; width: 10%">Số câu</th>
                <th style="text-align:center; width: 15%">Điểm</th>
                <th style="text-align:center; width: 15%">Thời gian làm bài</th>
                <th style="text-align:center; width: 10%">Chi tiêt bài làm</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $USER = new \Learncom\Repositories\User();
            foreach ($arrScore as $score) {
                $test_model = \Learncom\Repositories\Test::findFirstById($score->getScoreTestId());
                if ($test_model) {
                    if ($test_model->getTestParentId() != 0) {
                        $test_model = \Learncom\Repositories\Test::findFirstById($test_model->getTestParentId());
                    }

                ?>
                    <script>
                        $(function(){
                            $('#delete<?= $score->getScoreId()?>').live("click",function(e){
                                e.preventDefault();
                                $('#warn').modal('show');
                                var id=$("#<?= $score->getScoreId();?>").attr("data-browse");
                                var test_id = "<?= $test_model->getTestId()?>";
                                $("#class_id").val(id);
                                $("#test_id").val(test_id);
                                var str="Bạn của muốn xóa bài thi này của "+"<?php echo $USER->getNameByID($score->getScoreUserId()); ?>";
                                $("#message").text(str);

                            });
                        });
                    </script>
                <tr>
                    <td id="<?= $score->getScoreId();?>" data-browse="<?= $score->getScoreId();?>"><?= \Learncom\Repositories\Test::getTestName($test_model->getTestId()) ?></td>
                    <td><?= \Learncom\Repositories\Test::getTestClass($test_model->getTestId()) ?></td>
                    <td><?= $test_model ? $test_model->getTestNumberQuestion() : 0 ?></td>
                    <td><?= $score->getScoreScore() ?></td>
                    <td><?= $score->getScoreTime() ?> (Phút)</td>
                    <td  style="text-align:center;" class="center">
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('/dashboard/detail-user-test');?>?id=<?= $score->getScoreTestId()?>&user-id=<?=$score->getScoreUserId()?>">
                            <i class="icon-edit icon-white"></i>
                            View
                        </a>
                        <a id="delete<?php echo $score->getScoreId();?>" class="btn btn-danger" href="">delelte</a>
                    </td>
                </tr>

            <?php }  } ?>
            </tbody>
        </table>
    </div>
</form>
<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="class_id" name="class_id" />
            <input type="hidden" id="test_id" name="test_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<script>
    $(document).ready(function() {
        $('#create_article').on('click', function () {
            history.back()
        });
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('/dashboard/delete-score');?>";
            var id= $("#class_id").val();
            var test_id= $("#test_id").val();
            str=str.concat("?id=").concat(id);
            str = str.concat("&testId=").concat(test_id);
            $('#delete').attr("href",str);
        });
    });
</script>
