
<?php if(isset($msg_result['status']))  {?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status']?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form" id="read_form" method="post" >
    <div class="box-content">
        <h3>Danh sách học sinh làm bài thi: <?= $testName ?></h3>
        <a href="<?php echo $this->url->get('dashboard/list-summary')?>" name="create_article" id="create_article" class="btn btn-primary pull-lefy">Back</a>
        <a class="btn btn-primary pull-lefy" id="sbmCSV" name="sbmCSV">Xuất File Excel</a>
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center; width: 15%">Tên Học sinh</th>
                <th style="text-align:center; width: 10%">Lớp</th>
                <th style="text-align:center; width: 10%">Điểm Trắc Nghiệm</th>
                <th style="text-align:center; width: 10%">Điểm Tự luận</th>
                <th style="text-align:center; width: 10%">Tổng Điểm</th>
                <th style="text-align:center; width: 10%">Thời gian hoàn thành</th>
                <th style="text-align:center; width: 10%">Thời gian Làm bài</th>
                <th style="text-align:center; width: 15%">Chi tiêt bài làm</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $USER = new \Learncom\Repositories\User();
            foreach($arrScore as  $score){
                ?>
                <script>
                    $(function(){
                        $('#delete<?= $score->getScoreId()?>').live("click",function(e){
                            e.preventDefault();
                            $('#warn').modal('show');
                            var id=$("#<?= $score->getScoreId();?>").attr("data-browse");
                            var test_id = "<?= $test_model->getTestId()?>";
                            $("#class_id").val(id);
                            $("#test_id").val(test_id);
                            var str="Bạn của muốn xóa bài thi này của "+"<?php echo $USER->getNameByID($score->getScoreUserId()); ?>";
                            $("#message").text(str);

                        });
                    });
                </script>
                <tr>
                    <td  style="text-align:left;" id="<?= $score->getScoreId();?>" data-browse="<?= $score->getScoreId();?>" class="center">
                        <?php echo $USER->getNameByID($score->getScoreUserId()); ?>
                    </td>

                    <td  style="text-align:left;">
                        <?= \Learncom\Repositories\ClassSubject::getNameByClassAndSubject($test_model->getTestClassId(),$test_model->getTestSubjectId())?>
                    </td>
                    <td  style="text-align:left;">
                        <input name="txtScoreIsChose<?= $score->getScoreId() ?>" id="txtScoreIsChose<?= $score->getScoreId() ?>" class="point" data-browse="<?= $score->getScoreId() ?>"  value="<?= $score->getScoreScoreChoose(); ?>">
                    </td>
                    <td  style="text-align:left;">
                        <input name="txtScoreNotChose<?= $score->getScoreId() ?>" id="txtScoreNotChose<?= $score->getScoreId() ?>"  class="point" data-browse="<?= $score->getScoreId() ?>" value="<?= (intval($score->getScoreScore()) - intval($score->getScoreScoreChoose())); ?>">
                    </td>
                    <td  style="text-align:left;">
                        <p id="totalScore<?= $score->getScoreId() ?>"><?= $score->getScoreScore(); ?></p>
                        <input hidden id="txtScore<?= $score->getScoreId() ?>"  name="txtScore<?= $score->getScoreId() ?>" value="<?= $score->getScoreScore(); ?>">
                    </td>
                    <td  style="text-align:left;">
                        <?= $score->getScoreTime() ?>
                    </td>
                    <td  style="text-align:left;">
                        <?= $this->my->formatDateTime($score->getScoreInsertTime()); ?>
                    </td>
                    <td  style="text-align:center;"class="center">
                        <button id="sbmSave<?= $score->getScoreId() ?>" name="sbmSave" value="<?php echo $score->getScoreId();?>" class="btn btn-danger" href="">Lưu Điểm</button>
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('/dashboard/detail-user-test');?>?id=<?= $score->getScoreTestId()?>&user-id=<?=$score->getScoreUserId()?>">
                            <i class="icon-edit icon-white"></i>
                            Bai lam
                        </a>
                        <a id="delete<?php echo $score->getScoreId();?>" class="btn btn-danger" href="">delelte</a>
                    </td>

                </tr>
            <?php } ?>
            </tbody>
        </table>
        <a href='#' onclick='downloadCSV({ filename: "KQ_Ktra.csv" });'>
            Download CSV
        </a>
    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="class_id" name="class_id" />
            <input type="hidden" id="test_id" name="test_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<script>
    $(document).ready(function() {
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('/dashboard/delete-score');?>";
            var id= $("#class_id").val();
            var test_id= $("#test_id").val();
            str=str.concat("?id=").concat(id);
            str = str.concat("&testId=").concat(test_id);
            $('#delete').attr("href",str);
        });
        $(".point").on('change',function () {
            var id = $(this).attr('data-browse');
            var score = parseFloat($('#txtScoreIsChose'+id).val()) +  parseFloat($('#txtScoreNotChose'+id).val());
            $('#totalScore'+id).html(score);
            $('#txtScore'+id).val(score);
            if (parseFloat($('#txtScoreIsChose'+id).val()) > 10) {
                $('#txtScoreIsChose'+id).addClass("border-red");
                $('#sbmSave'+id).attr('disabled',true);
            } else {
                $('#txtScoreIsChose'+id).removeClass("border-red");
                $('#sbmSave'+id).attr('disabled',false);
            }
            if (parseFloat($('#txtScoreNotChose'+id).val()) > 10) {
                $('#txtScoreNotChose'+id).addClass("border-red");
                $('#sbmSave'+id).attr('disabled',true);
            }else {
                $('#txtScoreNotChose'+id).removeClass("border-red");
                $('#sbmSave'+id).attr('disabled',false);
            }
            if (parseFloat($('#txtScore'+id).val()) > 10) {
                $('#txtScore'+id).parent().addClass("border-red");
                $('#sbmSave'+id).attr('disabled',true);
            }else {
                $('#txtScore'+id).parent().removeClass("border-red");
                $('#sbmSave'+id).attr('disabled',false);
            }
        });
        var userData;
        $('#sbmCSV').on('click', function () {
            var id = "<?= $test_id ?>"
            $.ajax({
                url: "<?php echo $this->url->get("/dashboard/get-csv")?>",
                async: false,
                type: "POST",
                dataType: "JSON",
                data: {'id': id,
                },
                success: function(data){
                    userData = data;
                    downloadCSV({ filename: "user data.csv" });
                }
            });
        });
        convertArrayOfObjectsToCSV = args => {
            const data = args.data;
            if (!data || !data.length) return;

            const columnDelimiter = args.columnDelimiter || ',';
            const lineDelimiter = args.lineDelimiter || '\n';

            const keys = Object.keys(data[0]);

            let result = '';
            result += keys.join(columnDelimiter);
            result += lineDelimiter;

            data.forEach(item => {
                ctr = 0;
            keys.forEach(key => {
                if (ctr > 0) result += columnDelimiter;
            result += item[key];
            ctr++;
        });
            result += lineDelimiter;
        });

            return result;
        }
        downloadCSV = args => {
            let csv = convertArrayOfObjectsToCSV({
                data: userData
            });
            if (!csv) return;

            const filename = args.filename || 'export.csv';

            if (!csv.match(/^data:text\/csv/i)) {
                csv = 'data:text/csv;charset=utf-8,\uFEFF' + csv;
            }

            const data = encodeURI(csv);

            const link = document.createElement('a');
            link.setAttribute('href', data);
            link.setAttribute('download', filename);
            link.click();
        }
    });
</script>