
<form name="read_form" id="read_form"  >
    <div class="box-content">
        <h3>Danh sách các bài thi trong: <?= $name ?></h3>
        <a href="<?php echo $this->url->get('dashboard/list-summary')?>" name="create_article" id="create_article" class="btn btn-primary pull-lefy">Back</a>
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center; width: 30%">Bài thi</th>
                <th style="text-align:center; width: 20%">Thuộc Nhóm</th>
                <th style="text-align:center; width: 10%">Số học sinh đã làm</th>
                <th style="text-align:center; width: 10%">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($arrTest as  $test){
                $arrTestParent = \Learncom\Repositories\Test::getArrTestParentId($test->getTestId());
                $total = 0;
                foreach ($arrTestParent as $test_parent) {
                    $test_parent_model = \Learncom\Repositories\Test::findFirstById($test_parent);
                    $arrTemp = $test_parent_model->score;
                    $total += count($arrTemp);
                }
                ?>
                <tr>
                    <td  style="text-align:left;" class="center">
                        <?php echo $test->getTestName(); ?>
                    </td>

                    <td  style="text-align:left;">
                        <?= \Learncom\Repositories\Group::getNameById($test->getTestGroupId()); ?>
                    </td>
                    <td  style="text-align:left;">
                        <?= $total; ?>
                    </td>
                    <td  style="text-align:center;"class="center">
                        <a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get('/dashboard/detail-list-test');?>?id=<?= $test->getTestId()?>">
                            <i class="icon-edit icon-white"></i>
                            View
                        </a>
                    </td>

                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="class_id" name="class_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>