
<form name="read_form" id="read_form"  >
    <div class="box-content">
        <h3>Danh sách các học sinh trong: <?= $name ?></h3>
        <a href="<?php echo $this->url->get('dashboard/list-summary')?>" name="create_article" id="create_article" class="btn btn-primary pull-lefy">Back</a>
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
            <tr>
                <th style="text-align:center; width: 10%">ID</th>
                <th style="text-align:center; width: 30%">Tên</th>
                <th style="text-align:center; width: 10%">Số bài làm</th>
                <th style="text-align:center; width: 10%">Số điểm trung bình</th>
                <th style="text-align:center; width: 10%">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($arrUser as  $user){
                $arrScore = $user->score;
                $total_score = 0;
                foreach ($arrScore as $score) {
                    $total_score += $score->getScoreScore();
                }
                    ?>
                    <tr>
                        <td  style="text-align:left;" class="center">
                            <?php echo $user->getUserCode(); ?>
                        </td>

                        <td  style="text-align:left;">
                            <?= $user->getUserName(); ?>
                        </td>
                        <td  style="text-align:left;">
                            <?= count($arrScore); ?>
                        </td>
                        <td  style="text-align:left;">
                            <?= count($arrScore) == 0 ? 0 : $total_score/count($arrScore); ?>
                        </td>
                        <td  style="text-align:center;"class="center">
                            <a id="edit_account" class="btn btn-success" href="<?php echo $this->url->get('dashboard/detail-test');?>?id=<?= $user->getUserId()?>">
                                <i class="icon-edit icon-blue"></i>
                                Các bài Ktra
                            </a>
                        </td>

                    </tr>
                <?php } ?>
            </tbody>
        </table>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="class_id" name="class_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>