<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-red">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Warning!</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="id" name="id"/>
                <p class="content-warning"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
                <a class="btn btn-primary delete-all">Yes</a>
            </div>
        </div>
    </div>
</div>
<!-- footer content -->
<div id="loading" hidden style="position: fixed;z-index: 10000;top: 0px;left: 0px;width: 100%;height: 100%;background: #fff;filter: alpha(opacity=85);opacity: 1;background: rgba(255, 255,255,0);text-align: center; color:#f00;">
    <div style="background-color: #FDF7CC;border: 1px solid #FDC86C;border-radius: 4px;padding: 1px;margin: 20px auto;width: 50%;">
        <img src="<?php echo $this->url->getStatic('backoffice/img/waiting.gif'); ?>"
             alt='Processing'
             title='Processing'
             style="vertical-align:middle;position: relative;z-index: 10001;"/>. Please waiting for the system to run!
    </div>
</div>
<footer>
    <div class="pull-right">
        Copyright ©1997 - <?php echo date("Y", time()); ?> Chibao
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->
<div id="l-loading"
     style="position: fixed;z-index: 10000;top: 0;left: 0;width: 100%;height: 100%;filter: alpha(opacity=85);opacity: 1;text-align: center;display:none;">
    <div style="background-color: rgba(255, 255, 255, 0.9);width: 100%;height: 100%;">
        <img src="<?php echo $this->url->getStatic('backoffice/img/waiting.gif'); ?>"
             alt='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             title='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             style="vertical-align:middle;position: relative;z-index: 10001;top: calc(50% - 16px)">
    </div>
</div>
</div>
</div>


<!-- Bootstrap -->
<script src="<?php echo $this->url->getStatic('shared2/js/'); ?>bootstrap.min.js"></script>
<!--Datetime-->
<?php $controllerName = $this->dispatcher->getControllerName();
      $actionName = $this->dispatcher->getActionName();
if ($controllerName != 'user' || $actionName == 'index') {?>
    <script type="text/javascript" src="<?php echo $this->url->getStatic("/backoffice/js/datepicker.js"); ?>"></script>
<?php } ?>

<script type="text/javascript" src="<?php echo $this->url->getStatic("/backoffice/js/jquery.timepicker.js"); ?>"></script>
<!-- Custom Theme Scripts -->
<script src="<?php echo $this->url->getStatic('backoffice/js/'); ?>custom.min.js"></script>
<script src="<?php echo $this->url->getStatic('backoffice/js/'); ?>utils.js?v=<?php echo time(); ?>"></script>
<script src="<?php echo $this->url->getStatic('backoffice/js/'); ?>typeahead.bundle.js"></script>
<?php if (in_array($this->router->getControllerName(), array('ticket','topflight','topdestination'))) { ?>
    <script src="<?php echo $this->url->getStatic('backoffice/'); ?>js/autocomplete.js?v=<?=time() ?>"></script>
    <script src="<?php echo $this->url->getStatic('backoffice/'); ?>js/ajaxtypeahead.js?v=<?=time() ?>"></script>
<?php } ?>
</body>
</html>