<?php
use Learncom\Repositories\Role;
if (isset($role_function)) {
    $pre = 'backed';
    $menu_active = 'class="active"';
    $menu_sub_active = 'style="display: block;"';
    $menu_sub_sub_active = 'class="current-page"';
    $controllers = Role::getControllers();
    $controllerName = $this->dispatcher->getControllerName();


}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="<?php echo $this->url->get("/"); ?>" class="site_title"><i class="fa fa-institution"></i>
                <span>Thi Online </span></a>
        </div>
        <div class="clearfix"></div>
        <br/>
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <?php
                    if (Role::checkiMenuItem($role_function, "schoolclass")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "schoolclass") ? $menu_active : ""; ?> >
                            <a href="<?php echo $this->url->get("/office/list-new-class"); ?>"><i class="fa fa-book"></i>Lớp học</a></li>
                    <?php } ?>
                    <?php
                    if(Role::checkiMenuItem($role_function, "schoolstudent")) { ?>
                        <li <?php echo $this->dispatcher->getControllerName() === "schoolstudent" ? $menu_active:""; ?>  ><a><i class="fa fa-user-plus"></i>Quản lý học sinh  <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu"  <?php echo $this->dispatcher->getControllerName() === "schoolstudent" ? $menu_sub_active:""; ?> >
                                <li <?php echo ($this->dispatcher->getControllerName() === "schoolstudent" && isset($school_class_id) && $school_class_id == "all")?$menu_sub_sub_active:""; ?> >
                                    <a href="<?php echo $this->url->get("/office/list-new-student");?>">Tất cả lớp</a>
                                </li>

                                <?php foreach ($arraySchoolClass as $class) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "schoolstudent" && isset($school_class_id) && $school_class_id == $class->getClassId())?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/office/list-new-student?slcClass=".$class->getClassId());?>"> <?= $class->getClassName()?></a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </li>
                        </li>
                    <?php } ?>
                    <?php
                    if (Role::checkiMenuItem($role_function, "schooltest")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "schooltest") ? $menu_active : ""; ?> >
                            <a href="<?php echo $this->url->get("/office/list-new-test"); ?>"><i class="fa fa-book"></i>Đề thi</a></li>
                    <?php } ?>
                    <?php
                    if (Role::checkiMenuItem($role_function, "schoolexamtest")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "schoolexamtest") ? $menu_active : ""; ?> >
                            <a href="<?php echo $this->url->get("/office/list-new-exam-test"); ?>"><i class="fa fa-book"></i>Nhóm đề thi</a></li>
                    <?php } ?>
                    <?php if(Role::checkiMenuItem($role_function, "schoolmanage")) { ?>
                        <li <?php echo $this->dispatcher->getControllerName() === "schoolmanage" ? $menu_active:""; ?>  ><a><i class="fa fa-user-plus"></i>Quản lý thi  <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu"  <?php echo ($this->dispatcher->getControllerName() === "schoolmanage")?$menu_sub_active:""; ?> >
                                <?php foreach ($arraySchoolClass as $class) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "schoolmanage" && isset($school_class_id) && $school_class_id == $class->getClassId())?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/office/student-new-test?id=".$class->getClassId());?>"> <?= $class->getClassName()?></a>
                                    </li>

                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>