
<script>
	$(document).ready(function(){
		$("#search").click(function(){
			$("#read_form").prop("action","<?php echo $this->url->get("dashboard/list-type");?>");
			$("#read_form").prop("method","post");
			$("#read_form").submit();
			});
		$('#delete').click(function(){
			var str="<?php echo $this->url->get('dashboard/delete-type');?>";
			var id=$("#type_id").val();
			str=str.concat("?id=").concat(id);
			$('#delete').attr("href",str);
			});
	});
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-type");?>'>List Type</a></li>");
</script>
    <?php
    if($this->request->get("type")!=NULL||$this->request->get("message")!=NULL)
    {
        ?>
        <p style="font-size:18px;text-align:center; margin-bottom: 15px" class="alert alert-<?php echo $this->request->get("type")?>">
            <?php echo $this->request->get("message"); ?>
        </p>
    <?php }	?>
<form name="read_form" id="read_form" method="POST">
<div>
<table>
						<?php
                                $keyword=$this->dispatcher->getParam("key_word");
                                $type_search=$this->dispatcher->getParam("parent");
                                $typeClass= new Learncom\Repositories\Type();
                                $strtype=$typeClass->getCombo(0,"",$type_search);
                                $list_type = $this->dispatcher->getParam("list_type");
 						?>
                        <tr>
                        	<th><input  placeholder="Keyword" value="<?php echo $keyword; ?>" name="txtSearchKeyword" id="txtSearchKeyword" type="text"/></th>
                            <th><select  id="txtSearchParent" name="txtSearchParent">
                                    <option value="">All Type</option>
                                    <?php echo $strtype?>
                                </select><th>
                        	<th><input  type="button" name="search" id="search" value="Search" class="btn btn-primary"/></th>
                            <th><a  class="btn btn-primary" href="<?php echo $this->url->get('dashboard/create-type');?>">Add New</a>
                                </th>
                        </tr>
</table>
</div>
<div class="box-content">
						
						<table class="table table-striped table-bordered bootstrap-datatable">
						  <thead>
							  <tr>
                              	  <th style="text-align:center;">Id</th>
								  <th style="text-align:center;width: 312px;">Name</th>
                                  <th style="text-align:center;">Parent</th>
                                  <th style="text-align:center;">Keyword</th>
                                  <th style="text-align:center;">Order</th>
                                  <th style="text-align:center;">Active</th>
                                  <th style="text-align:center;width: 150px;">Action</th>
							  </tr>
						  </thead>   
						  <tbody>
                           <?php
						   if($list_type){
								foreach($list_type as $type){
									$id = $type->getTypeId();
									$type_name = $typeClass->getName($id);
						   ?>
                           <script>
                         	$(function(){
								$('#delete<?php echo $type->getTypeId();?>').click(function (e) {
										e.preventDefault();
										$('#warn').modal('show');
										var id=$("#<?php echo $type->getTypeId();?>").text();
										$("#type_id").val(id);
										var str="Are you sure to remove Type ID = ".concat(id) + " and Type children and Aritlce";
										$("#message").text(str);
										});
								});						 
                             </script>
                          	<tr>
                                <td style="text-align:center;"id="<?php echo $type->getTypeId();?>"><?php echo $type->getTypeId();?></td>
								<td style="text-align:left;"class="center"><?php echo $type_name;?></td>
                                <td style="text-align:center;"class="center"><?php echo $typeClass->getName($type->getTypeParentId());?></td>
                                <td style="text-align:center;"class="center"><?php echo $type->getTypeKeyword();?></td>
                                <td style="text-align:center;"class="center"><?php echo $type->getTypeOrder();?></td>
                                <td style="text-align:center;"class="center"><?php echo $type->getTypeActive();?></td>
                                <td style="text-align:center;" class="center">
									<a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get("dashboard/edit-type");?>?id=<?php echo $type->getTypeId();?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a id="delete<?php echo $type->getTypeId();?>" class="btn btn-danger delete_account" href="#">										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
								</td>
							</tr>
							<?php } }?>
						  </tbody>
					  </table>    
                          <div class="pagination pagination-centered">
						  <ul>
                              <?php $crr_page=$this->dispatcher->getParam("current_page");
                              $total_page = $this->dispatcher->getParam("total_page");
                              $total=$this->dispatcher->getParam("all_records");
                              ?>
                          <?php if ($crr_page != 1){?>
							<li><a id="prev"  href="<?php echo $this->url->get('dashboard/list-type')?>?page=<?php echo $crr_page-1;?>&txtSearchKeyword=<?php echo $keyword;?>&txtSearchParent=<?php echo $type_search;?>">Prev</a></li>
                            <?php }?>
							<?php
							$n=floor($total_page/10);
							$b=$total_page%10;
							$flag=0;
							$limit=0;
							if($crr_page >=1){
								$flag=floor($crr_page/10);
								if($flag<$n){
									$limit=($flag*10)+10;
								}else{
									$limit=($flag*10)+$b;
								}
							}
							if($crr_page < $limit){
								$start=0;
								if($flag==0)
									$start=$flag*10+1;
								else
									$start=$flag*10;
								for($i=$start;$i <=$limit;$i++){
										if($i==$crr_page){
							 ?>
                             <li><a style="color:#333" id="number_page"  href="<?php echo $this->url->get('dashboard/list-type')?>?page=<?php echo $i ?>&txtSearchKeyword=<?php echo $keyword;?>&txtSearchParent=<?php echo $type_search;?>"><?php echo $i ?></a></li>
                             <?php }else{?>
                             <li><a id="number_page" href="<?php echo $this->url->get('dashboard/list-type')?>?page=<?php echo $i ?>&txtSearchKeyword=<?php echo $keyword;?>&txtSearchParent=<?php echo $type_search;?>"><?php echo $i ?></a></li>
                             		<?php }?>
                            	 <?php }?>
                             <?php }?>
                             <?php if ($crr_page<$total_page){?>
							<li><a id="next"  href="<?php echo $this->url->get('dashboard/list-type')?>?page=<?php echo $crr_page+1;?>&txtSearchKeyword=<?php echo $keyword;?>&txtSearchParent=<?php echo $type_search;?>">Next</a></li>
                            <?php }?>
						  </ul>
						</div> 
                        <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?php echo $total?></strong> Types</p>

</div>
</form>

<!--FORM DELETE A TYPE-->

<form>
<div class="modal hide fade" id="warn">
	<div class="modal-header">
<input  type="hidden" id="type_id" name="type_id" />
<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Warning !</h3>
	</div>
	<div class="modal-body">
				<p id="message"></p>
	</div>
	<div class="modal-footer">
				<a href="" class="btn" data-dismiss="modal">Close</a>
				<a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
	</div>
</div>
</form>

