<main>
    <div class="login-wrap overflow-auto">
        <div class="container pt-xs-60 pt-40 pb-xs-70">
            <div class="form-log-emal">
                <h1 class="title-main">Thông báo</h1>
                <div class="p-40 p-xs-20 mt-30 bg-white fit-center max-w-100 rounded-lg">
                    <p class="text-danger text-medium text-center">Bạn không có quyền truy cập vào đây. Vui lòng đăng nhập hoặc liên hệ quản trị viên!</p>
                    <p class="text-right"><a href="/" class="btn btn-info">Quay về trang chủ</a></p>
                </div>
            </div>
        </div>
    </div>
</main>