<script>
    $(document).ready(function(){
        $(window).keydown(function(event){
            if(event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });
        $("#create_user").click(function(){
            $("#read_form").prop("action","<?php echo $this->url->get("dashboard/create-user");?>");
            $("#read_form").prop("method","post");
            $("#read_form").submit();

        });
        $("#search").click(function(){
            $("#read_form").prop("action","<?php echo $this->url->get("dashboard/list-user");?>");
            $("#read_form").prop("method","post");
            $("#read_form").submit();

        });
        $('#delete').click(function(){
            var str="<?php echo $this->url->get('dashboard/delete-user');?>";
            var id=$("#user_id").val();
            str=str.concat("?id=").concat(id);
            $('#delete').attr("href",str);
        });

    });
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-user");?>'>List User </a></li>");
</script>
<?php
if($this->request->get("type")!=NULL||$this->request->get("message")!=NULL)
{
    ?>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $this->request->get("type")?>">
        <?php echo $this->request->get("message"); ?>
    </p>
<?php }	?>
    <form name="read_form" id="read_form"  >
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable">
                <thead>
                <tr>
                    <th style="text-align:center;">ID</th>
                    <th style="text-align:center;">Fullname</th>
                    <th style="text-align:center;">Role</th>
                    <th style="text-align:center;">Email</th>
                    <th style="text-align:center;">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php $list_item = $this->dispatcher->getParam("list_item");
                foreach($list_item as $item){
                    ?>
                    <script>
                        $(function(){
                            $('#delete<?php echo $item->user_id?>').live("click",function(e){
                                e.preventDefault();
                                $('#warn').modal('show');
                                var id=$("#<?php echo $item->user_id;?>").text();
                                $("#user_id").val(id);
                                var str="Are you sure to remove user ID = ".concat(id);
                                $("#message").text(str);

                            });
                        });
                    </script>
                    <tr>

                        <td style="text-align:center;" class="center" id="<?php echo $item->user_id; ?>"><?php echo $item->user_id; ?></td>
                        <td  style="text-align:left;" class="center">
                            <?php echo $item->user_name; ?>
                        </td>
                        <td  style="text-align:center;" class="center">
                            <?php echo $item->user_role; ?>
                        </td>
                        <td  style="text-align:left;">
                            <?php echo $item->user_email; ?>
                        </td>
                        <td  style="text-align:center;" class="center">
                            <a href="<?php echo $this->url->get("dashboard/edit-user")?>?id=<?php echo $item->user_id;?>" title="Cập nhật User Id <?php echo $item->user_id; ?>" target="_self" class="btn btn-info">
                                Edit
                            </a>
                            <a id="delete<?php echo $item->user_id;?>" class="btn btn-danger delete_account" href="#" title="Delete User Id <?php echo $item->user_id; ?>"><i class="icon-trash icon-white"></i>
                                Delete
                            </a>
                        </td>

                    </tr>
                <?php }?>
                </tbody>
            </table>
            <div class="pagination pagination-centered">
                <ul>
                    <?php $crr_page=$this->dispatcher->getParam("current_page");
                    $total_page = $this->dispatcher->getParam("total_page");
                    ?>

                    <?php if ($crr_page != 1){?>
                        <li><a id="prev"  href="<?php echo $this->url->get('dashboard/list-user')?>?txt_keyword=<?php echo $this->dispatcher->getParam("txt_keyword");?>&page=<?php echo $crr_page-1;?>">Prev</a></li>
                    <?php }?>
                    <?php
                    $n=floor($total_page/10);
                    $b=$total_page%10;
                    $flag=0;
                    $limit=0;
                    if($crr_page >=1){
                        $flag=floor($crr_page/10);
                        if($flag<$n){
                            $limit=($flag*10)+10;
                        }else{
                            $limit=($flag*10)+$b;
                        }
                    }
                    if($crr_page < $limit){
                        $start=0;
                        if($flag==0)
                            $start=$flag*10+1;
                        else
                            $start=$flag*10;
                        for($i=$start;$i <=$limit;$i++){
                            if($i==$crr_page){
                                ?>
                                <li><a style="color:#333" id="number_page"  href="<?php echo $this->url->get('dashboard/list-user')?>?txt_keyword=<?php echo $this->dispatcher->getParam("txt_keyword");?>&page=<?php echo $i ;?>"><?php echo $i ?></a></li>
                            <?php }else{?>
                                <li><a id="number_page" href="<?php echo $this->url->get('dashboard/list-user')?>?txt_keyword=<?php echo $this->dispatcher->getParam("txt_keyword");?>&page=<?php echo $i ;?>"><?php echo $i ?></a></li>
                            <?php }?>
                        <?php }?>
                    <?php }?>
                    <?php if ($crr_page<$total_page){?>
                        <li><a id="next"  href="<?php echo $this->url->get('dashboard/list-user')?>?txt_keyword=<?php echo $this->dispatcher->getParam("txt_keyword");?>&page=<?php echo $crr_page+1;?>">Next</a></li>
                    <?php }?>
                </ul>
            </div>
            <div style="float:left">
                <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?php echo $this->dispatcher->getParam("all_records");?></strong> Users</p>
            </div>
            <div style="clear:left"></div>
        </div>
    </form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input  type="hidden" id="user_id" name="user_id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>