 <script>
       		
				$(document).ready(function(){
						$("#cancel").click(function(){
						$("#create_form").prop("action","<?php echo $this->url->get("dashboard/list-activity");?>");
						$("#create_form").prop("method","post");
						$("#create_form").submit();
						});
					});

</script>

<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-edit"></i> Form View  Activities:</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<form novalidate="novalidate" class="form-horizontal" id="create_form" action=""
                        method="post">
                       
							<fieldset>
                            <?php $act=$this->dispatcher->getParam("act");
                            $userRepo = $this->dispatcher->getParam("userRepo");
							$user = $userRepo->findByID($act->getActUserId());
							?>
                                <h3>Activity Information:</h3>
                                <table class="table table-striped table-bordered bootstrap-datatable">
                                    <tr>
                                        <td style="text-align:left; width: 200px">ID</td>
                                        <td ><?php echo $act->getActId(); ?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Controller</td>
                                        <td ><?php echo $act->getActController();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Action</td>
                                        <td ><?php echo $act->getActAction();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Action ID</td>
                                        <td ><?php
                                            if($act->getActController()=="contactus"){
                                                echo $this->my->formatContactID($act->getActCreateDate(),$act->getActActionId());
                                            }else
                                            {
                                                echo $act->getActActionId();
                                            }

                                            ?></td>
                                    </tr>
                                    <?php if($user){?>
                                    <tr>
                                        <td style="text-align:left; width: 200px">User</td>
                                        <td >ID: #<?php echo $act->getActUserId();?><br/>Name: <?php echo $user->getUserName(); ?><br/>Email: <?php echo $user->getUserEmail(); ?></td>
                                    </tr>
                                    <?php }?>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Date Created:</td>
                                        <td ><?php echo date('M/d/Y - H:i:s',$act->getActCreateDate()); ?></td>
                                    </tr>
                                </table>
                                <h3>Location Information:</h3>
                                <table class="table table-striped table-bordered bootstrap-datatable">
                                    <tr>
                                        <td style="text-align:left; width: 200px">IP</td>
                                        <td ><?php echo $act->getActIp(); ?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Location</td>
                                        <td ><?php echo $act->getActLocation();?></td>
                                    </tr>
                                </table>
                                <h3>Device Information:</h3>
                                <table class="table table-striped table-bordered bootstrap-datatable">
                                    <tr>
                                        <td style="text-align:left; width: 200px">Computer Screen</td>
                                        <td ><?php echo $act->getActComputerScreen(); ?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Window Size</td>
                                        <td ><?php echo $act->getActBrowserWindowSize();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Hardware Type</td>
                                        <td ><?php echo $act->getActHardwareType();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Name</td>
                                        <td ><?php echo $act->getActOperatingSystemName();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Software Sub Type</td>
                                        <td ><?php echo $act->getActSoftwareSubType();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Sub Description</td>
                                        <td ><?php echo $act->getActSimpleSubDescriptionString();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Browser</td>
                                        <td ><?php echo $act->getActSimpleBrowserString();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Version</td>
                                        <td ><?php echo $act->getActBrowserVersion();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Software Type</td>
                                        <td ><?php echo $act->getActSoftwareType();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Extra Info</td>
                                        <td ><?php echo $act->getActExtraInfo();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating Platform</td>
                                        <td ><?php echo $act->getActOperatingPlatform();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Extra Info Table</td>
                                        <td ><?php echo $act->getActExtraInfoTable();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Layout Engine Name</td>
                                        <td ><?php echo $act->getActLayoutEngineName();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Flavour Code</td>
                                        <td ><?php echo $act->getActOperatingSystemFlavourCode();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Detected Addons</td>
                                        <td ><?php echo $act->getActDetectedAddons();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Flavour</td>
                                        <td ><?php echo $act->getActOperatingSystemFlavour();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Frameworks</td>
                                        <td ><?php echo $act->getActOperatingSystemFrameworks();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Name Code</td>
                                        <td ><?php echo $act->getActBrowserNameCode();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Minor</td>
                                        <td ><?php echo $act->getActSimpleMinor();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Version</td>
                                        <td ><?php echo $act->getActOperatingSystemVersion();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Operating Platform</td>
                                        <td ><?php echo $act->getActSimpleOperatingPlatformString();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Abusive</td>
                                        <td ><?php echo $act->getIsAbusive();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Medium</td>
                                        <td ><?php echo $act->getActSimpleMedium();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Layout Engine Version</td>
                                        <td ><?php echo $act->getActLayoutEngineVersion();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Capabilities</td>
                                        <td ><?php echo $act->getActBrowserCapabilities();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating Platform Vendor Name</td>
                                        <td ><?php echo $act->getActOperatingPlatformVendorName();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System</td>
                                        <td ><?php echo $act->getActOperatingSystem();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Hardware Architecture</td>
                                        <td ><?php echo $act->getActHardwareArchitecture();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Version Full</td>
                                        <td ><?php echo $act->getActOperatingSystemVersionFull();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating Platform Code</td>
                                        <td ><?php echo $act->getActOperatingPlatformCode();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Name</td>
                                        <td ><?php echo $act->getActBrowserName();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Operating System Name Code</td>
                                        <td ><?php echo $act->getActOperatingSystemNameCode();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">User Agent</td>
                                        <td ><?php echo $act->getActUserAgent();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Simple Major</td>
                                        <td ><?php echo $act->getActSimpleMajor();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser Version Full</td>
                                        <td ><?php echo $act->getActBrowserVersionFull();?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:left; width: 200px">Browser</td>
                                        <td ><?php echo $act->getActBrowser();?></td>
                                    </tr>
                                </table>

							 <div class="form-actions">
								<button type="submit" id="cancel" class="btn btn-primary">Back List</button>
							  </div>
                             
							</fieldset>
                            
						  </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
           <script>
$(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-activity");?>'>List Activities</a></li> / <li><a href='<?php echo $this->url->get("dashboard/view-activity?id=".$act->getActId());?>'>Activity Details</a></li>");
</script>