
<script>

    $(document).ready(function(){
       
   $('#fileUpload').on("change",function() {
            if ($('#fileUpload')[0].files[0]) {
            var reader = new FileReader();            
            reader.onload = function (e) {
                $('#image-fileUpload').attr('src', e.target.result);
            }
            reader.readAsDataURL($('#fileUpload')[0].files[0]);
        }

    });
        $("#create_form").submit(function(){
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Bạn cần nhập thông tin này');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Bạn cần nhập thông tin này');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Bạn cần nhập thông tin này');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }

            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });
    });

</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-article");?>'>List Blog</a><span class='divider'>/</span></li><li><a href='<?php echo $this->url->get("dashboard/create-article");?>'>Create Blog</a></li>");
</script>
<?php
if(!empty($formData['message']))
{
    ?>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $formData['typeMessage']?>">
        <?php echo $formData['message']; ?>
    </p>
<?php }	?>
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i><?= isset($formData['mode']) ? $formData['mode'] : "" ?> Lịch Khai giảng :</h2>
            <div class="box-icon"> <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a> <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a> <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a> </div>
        </div>
        <div class="box-content">
            <form novalidate="novalidate" class="form-horizontal" id="create_form" action="" method="post"  enctype="multipart/form-data">
                <fieldset>
                    <div class="control-group">

                        <label class="control-label" for="focusedInput">Tên <em style="color:red;">*</em></label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['article_name']) ? $formData['article_name'] : ""?>"
                                   maxlength="256" id="txtName" name="txtName" class="input-xlarge focused <?php echo isset($messages["article_name"]) ? $messages["status"] : "";?>"  type="text" >
                            <div class="text-danger msg-name"><?php echo isset($messages["article_name"]) ? $messages["article_name"] : "";?></div>

                        </div>
                    </div>
                    <div class="control-group">

                        <label class="control-label" for="focusedInput">Keyword <em style="color:red;">*</em></label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['article_keyword']) ? $formData['article_keyword'] : ""?>"
                                   maxlength="256" id="txtKeyword" name="txtKeyword" class="input-xlarge focused <?php echo isset($messages["article_keyword"]) ? $messages["status"] : "";?>"  type="text" >
                            <div class="text-danger msg-keyword"><?php echo isset($messages["article_keyword"]) ? $messages["article_keyword"] : "";?></div>

                        </div>
                    </div>
                    <div class="control-group">

                        <label class="control-label" for="focusedInput">Icon </label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['article_icon']) ? $formData['article_icon'] : ""?>"
                                   maxlength="256" id="txtIcon" name="txtIcon" class="input-xlarge focused >"  type="text" >

                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Order <em style="color:red;">*</em> </label>
                        <div class="controls">
                            <input value="<?php echo isset($formData['article_order']) ? $formData['article_order'] : "" ?>"
                                   id="txtOrder" name="txtOrder" class="input-xlarge focused  <?= isset($messages["article_order"]) ? $messages["status"] : "";?>"    maxlength="10"  type="text" >
                            <div class="text-danger msg-order"><?php echo isset($messages["article_order"]) ? $messages["article_order"] : "";?></div>

                        </div>
                    </div>

                    <div class="control-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class=" controls">
                            <label class="checkbox"><input  type="radio" name="radActive" value="Y" <?php echo (isset($formData["article_active"]) && $formData["article_active"] == "Y") ? "checked" : ''; ?>>
                                                                  Yes
                                                                  <span class="check_active"></span></label>
                            <label class="checkbox"><input  type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["article_active"]) && $formData["article_active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="check_active"></span></label>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="textarea2">Summary </label>
                        <div class="controls">
                            <textarea style="width: 500px;height: 200px" id="txtSummary" name="txtSummary"><?php echo isset($formData['article_summary']) ? $formData['article_summary'] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="control-group">
                       
                    <label class="control-label" for="upload-files">Hình ảnh<em style="color:red;">*</em></label>

                       
                    
                    <div class="controls">
                    <?php
                        if ($formData['article_content']) :
                        ?>
                    <label id="label-fileUpload" for="fileUpload"><img style="max-width: 300px" id="image-fileUpload" src="<?= $formData['article_content']?>" /></label>
                    <?php else: ?>
                        <label id="label-fileUpload" for="fileUpload"><img style="max-width: 300px" id="image-fileUpload" src="/frontend/images/uploadfile.png" /></label>
                        <?php endif ?>
                        <input  id="fileUpload" name="fileUpload" type="file" class="hidden"
                            accept="<?php
                                foreach($this->globalVariable->acceptUploadTypes as $k => $v)
                                {
                                    echo $k.",";
                                } ?>"  />
                    </div>
                </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" id="submit_create">Save changes</button>
                        <a id="edit_page" class="btn" href="<?php echo $this->url->get('dashboard/list-article');?>"> Cancel </a> </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
                        window.onload = function () {
                            var oFCKeditor2 = new FCKeditor('txtSummary');
                            oFCKeditor2.Height = '500';
                            oFCKeditor2.Width = '650';
                            oFCKeditor2.ToolbarSet = "Default";
                            oFCKeditor2.Basepath = '../backend/fckeditor/';
                            oFCKeditor2.ReplaceTextarea();
                        }
                    </script>
