<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("txtSearchKeyword")) > 0) {
    if ($urlPage != "?")
        $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearchKeyword" => $this->dispatcher->getParam("txtSearchKeyword")));
}
$slcCountry = $this->dispatcher->getParam("slcClass");
if (strlen($this->dispatcher->getParam("slcClass")) > 0) {
    if ($urlPage != "?")
        $urlPage .= "&";
    $urlPage .= http_build_query(array("slcClass" => $this->dispatcher->getParam("slcClass")));
}
if (strlen($this->dispatcher->getParam("slcSubject")) > 0) {
    if ($urlPage != "?")
        $urlPage .= "&";
    $urlPage .= http_build_query(array("slcSubject" => $this->dispatcher->getParam("slcSubject")));
}
?>
<script>
    $(document).ready(function () {
        $('#delete').click(function () {
            var str = "<?php echo $this->url->get('dashboard/delete-student'); ?>";
            var id = $("#document-id").val();
            str = str.concat("?id=").concat(id);
            $('#delete').attr("href", str);
        });
        $('#reset').click(function () {
            var str = "<?php echo $this->url->get('dashboard/reset-student'); ?>";
            var id = $("#reset-id").val();
            str = str.concat("?id=").concat(id);
            $('#reset').attr("href", str);
        });
        $('#resetAll').click(function () {
            $('#read_form_user').append("<input hidden name='resetAllIp' value='resetAllIp'>)").submit();
        });
        $('#search').on('click', function () {
            $('form[name=read_form_user]').prop('action', '<?php echo $this->url->get('/dashboard/list-student'); ?>');
            $('form[name=read_form_user]').submit();
        });

    });
</script>
<script>
    $(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-student"); ?>'>  Học sinh </a></li>");
</script>

<?php if (isset($msg_result)) {

    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $msg_result['status'] ?>">
        <?= $msg_result["message"]; ?>
    </p>
<?php } ?>
<form name="read_form_user" id="read_form_user" method="post">
    <div>
        <table>
            <?php
            $keyword = $this->dispatcher->getParam("key_word");
            ?>

            <tr>
                <th><input placeholder="Keyword(Name)" value="<?= isset($keyword) ? $keyword : ""; ?>"
                        name="txtSearchKeyword" id="txtSearchKeyword" type="text" /></th>
                <th>
                    <select id="slcClass" name="slcClass">
                        <option value="">Tất cả lớp học</option>
                        <?php echo isset($select_class) ? $select_class : "" ?>
                    </select>
                </th>
                <th>
                    <select id="slcSubject" name="slcSubject">
                        <option value="">Tất cả môn học</option>
                        <?php echo isset($select_subject) ? $select_subject : "" ?>
                    </select>
                </th>
                <th>
                    <select id="dgnl" name="dgnl">
                        <option value="">Tất cả môn DGNL</option>
                        <?php echo isset($select_dgnl) ? $select_dgnl : "" ?>
                    </select>
                </th>
                <th>
                    <button type="button" name="search" id="search" value="Search"
                        class="btn btn-primary">Search</button>
                </th>
                <th style="width: 20%"><a href="<?php echo $this->url->get('dashboard/create-student') ?>"
                        name="create_article" id="create_article" class="btn btn-primary">Add New</a></th>
                <th width="40%" class="text-right">
                    <a type="button" name="resetAllIp" id="resetAllIp" value="resetAllIp" class="btn btn-danger ">Reset
                        All IP</a>
                </th>
            </tr>
        </table>
    </div>
    <div class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable">
            <thead>
                <tr>
                    <th style="text-align:center;width: 150px"><input type="checkbox" id="check_all"></th>
                    <th style="text-align:center;width: 150px">ID</th>
                    <th style="text-align:center;width: 200px">Name</th>
                    <th style="text-align:center;width: 200px">Email</th>
                    <th style="text-align:center;width: 200px">Ngày Đăng ký</th>
                    <th style="text-align:center;width: 200px">Môn học</th>
                    <th style="text-align:center;width: 200px">Lớp học</th>
                    <th style="text-align:center;width: 50px">Active</th>
                    <th style="text-align:center;width: 250px">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($list_item->items as $item) {
                    ?>
                    <script>
                        $(function () {

                            $('#reset<?= $item->getUserId() ?>').on("click", function (e) {
                                e.preventDefault();
                                $('#resetIp').modal('show');
                                var id = $("#<?= $item->getUserId(); ?>").text();
                                var name = "<?= $item->getUserName() ?>";
                                $("#reset-id").val(id);
                                var str = "Bạn có muốn reset IP học sinh tên: ".concat(name);
                                $("#messageReset").text(str);

                            });
                        });
                    </script>
                    <tr>

                        <td style="text-align:center;" class="center"><input type="checkbox" class="item_check"
                                name="checkItem" value="<?= $item->getUserId() ?>">
                        </td>
                        <td style="text-align:center;" class="center">
                            <?php echo $item->getUserCode(); ?>
                        <td id="<?php echo $item->getUserId(); ?>" hidden><?php echo $item->getUserId(); ?></td>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?php echo $item->getUserName(); ?>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?php echo $item->getUserEmail(); ?>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?php echo $this->my->formatDatetime($item->getUserInsertTime(), false); ?>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?= \Learncom\Repositories\ClassSubject::getNameSubjectByIds($item->getUserSubjectIds()); ?>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?= \Learncom\Repositories\ClassSubject::getNameClassByIds($item->getUserClassIds()); ?>
                        </td>
                        <td style="text-align:left;" class="center">
                            <?php
                            $status = $item->getUserActive();
                            $classStatus = ($status == "Y") ? "success" : "info";
                            ?>
                            <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                        </td>


                        <td style="text-align:center;" class="center">
                            <a id="reset<?php echo $item->getUserId(); ?>" class="btn btn-info" href="">reset Ip</a>
                            <a id="edit_account" class="btn btn-info"
                                href="<?php echo $this->url->get('dashboard/edit-student'); ?>?id=<?php echo $item->getUserId(); ?>">
                                <i class="icon-edit icon-white"></i>
                                View
                            </a>
                        </td>

                    </tr>
                <?php } ?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-6 ">
                <div style="float:left">
                    <p style="text-align:left;font-size:16px;color:red"><strong style="">Tổng cộng :
                            <?= $list_item->total_items; ?>
                        </strong> Học sinh</p>
                    <a id="delete_all_student" class="btn btn-danger" href="javascript:void(0)">Delete Item Selected</a>
                </div>
            </div>
            <div class="col-md-6 t pull-right">
                <?php if ($list_item->total_pages > 1) { ?>
                    <nav class="pagination pagination-centered">
                        <?php if ($urlPage != "?")
                            $urlPage .= "&";
                        $urlPage .= "page=";
                        echo $this->my->renderPagination($urlPage, $list_item->current, $list_item->total_pages, 2);
                        ?>
                    </nav>
                <?php } ?>
            </div>
        </div>

    </div>
</form>


<!--FORM DELETE A ARTICLE-->

<form>
    <div class="modal hide fade" id="warn">
        <div class="modal-header">
            <input type="hidden" id="document-id" name="document-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<form>
    <div class="modal hide fade" id="resetIp">
        <div class="modal-header">
            <input type="hidden" id="reset-id" name="reset-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="messageReset"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="reset" name="reset" href="" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<form>
    <div class="modal hide fade" id="resetAllIpModal">
        <div class="modal-header">
            <input type="hidden" id="reset-id" name="reset-id" />
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Warning !</h3>
        </div>
        <div class="modal-body">
            <p id="messageResetAll"></p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn" data-dismiss="modal">Close</a>
            <a id="resetAll" name="resetAll" class="btn btn-primary">Yes</a>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('#resetAllIp').on('click', function () {
            $('#resetAllIpModal').modal('show');
            var str = "Bạn có muốn reset IP cho tất cả học sinh  ";
            $("#messageResetAll").text(str);
        });
        $("#check_all").on('click', function () {
            if ($(this).attr('checked')) {
                $(".item_check").attr('checked', true);

            } else {
                $(".item_check").attr('checked', false);
            }
        });
        $("#delete_all_student").on('click', function () {
            $('#warn').modal('show');
            var checkedValue = [];
            $("input:checkbox[name=checkItem]:checked").each(function () {
                checkedValue.push($(this).val());
            });
            checkedValue = checkedValue.join(",");
            var str = "Bạn có muốn xóa những học sinh này?";
            $("#document-id").val(checkedValue);

            $("#message").text(str);
        });
    });
</script>