<main>
    <div class="form_wrapper">
        <div class="form_login">
            <h2>Welcome Back!</h2>
            <p>Dont have an account? <a href="#">Sign up</a></p>
            <form autoComplete="off" method="POST" name="formLogin" enctype="multipart/form-data" action="">
                <div class="input_wrapper">
                    <label for="email">Email <span class="text-danger">*</span></label>
                    <input type="email" name="txtEmail" id="email" value="<?php echo isset($formData['user_code']) ? $formData['user_code'] : '' ?>">
                    <span class="text-error msg-email"><?php echo isset($message['email']) ? $message['email'] : ""; ?></span>
                </div>
                <div class="input_wrapper _input--pasword">
                    <label for="password">Password <span class="text-danger">*</span></label>
                    <input type="password" name="txtPassword" id="password">
                    <div class="toggle-pass">
                        <span class="_show-password">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M13.7345 13.855C13.5098 14.1129 13.2388 14.3198 12.9378 14.4632C12.6367 14.6067 12.3116 14.6839 11.9821 14.6901C11.6525 14.6963 11.3251 14.6315 11.0195 14.4994C10.7139 14.3674 10.4362 14.1709 10.2031 13.9216C9.97007 13.6724 9.78632 13.3755 9.66287 13.0486C9.53942 12.7217 9.47879 12.3716 9.48461 12.0192C9.49042 11.6667 9.56256 11.3191 9.69672 10.9971C9.83087 10.6751 10.0243 10.3853 10.2655 10.145M16.86 17.1975C15.4614 18.3376 13.7584 18.9693 12 19C6.27273 19 3 12 3 12C4.01773 9.97167 5.42929 8.19955 7.14 6.80252L16.86 17.1975ZM10.2818 5.21002C10.845 5.06904 11.4216 4.99857 12 5.00002C17.7273 5.00002 21 12 21 12C20.5033 12.9937 19.911 13.9292 19.2327 14.7913L10.2818 5.21002Z" stroke="#A2A2A8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M3 2.5L21 21" stroke="#A2A2A8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>

                        </span>
                        <span class="_hide-password">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 12C3 12 6.27273 5 12 5C17.7273 5 21 12 21 12C21 12 17.7273 19 12 19C6.27273 19 3 12 3 12Z" stroke="#A2A2A8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M12 14C13.1046 14 14 13.1046 14 12C14 10.8954 13.1046 10 12 10C10.8954 10 10 10.8954 10 12C10 13.1046 10.8954 14 12 14Z" stroke="#A2A2A8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </span>
                    </div>
                    <span class="text-error msg-password"><?php echo isset($message['password']) ? $message['password'] : ""; ?></span>
                </div>
                <div class="text-right"><a href="#">Forgot password</a></div>
                <div class="mt-20">
                    <button type="button" name="btnLogin">
                        Đăng nhập
                    </button>
                </div>
            </form>
        </div>
    </div>
</main>
<script>
    commands.push(function () {
        $(document).ready(function () {
        $('button[name=btnLogin]').click(function (event) {
            var valid = true;
            if ($('input[name=txtEmail]').val() == '') {
                valid = false;
                $('.msg-email').text('Vui lòng nhập email');
                $('input[name=txtEmail]').addClass("has-error");
            }
            else {
                $('.msg-email').text('');
                $('input[name=txtEmail]').removeClass("has-error");
            }
            if($('input[name=txtPassword]').val() == ''){
                valid = false;
                $('input[name=txtPassword]').addClass("has-error");
                $('.msg-password').text('Vui lòng nhập mật khẩu');
            } else {
                $('.msg-password').text('');
                $('input[name=txtPassword]').removeClass("has-error");
            }
            if(!valid){
                event.preventDefault();
            } else {
                $('#l-loading').show();
                $('button[name=btnLogin]').prop('disabled', true);
                $('form[name=formLogin]').submit()
            }
        });
        function emailValid(email) {
            var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
            return re.test(email);
        }
    })
    });
</script>
</body>
</html>