<script>
	$(document).ready(function(){
          $("#search").click(function(){
			$("#read_form").prop("action","<?php echo $this->url->get("dashboard/list-banner");?>");
			$("#read_form").prop("method","post");
			$("#read_form").submit();
			});
		$('#delete').click(function(){
			var str="<?php echo $this->url->get('dashboard/delete-banner');?>";
			var id=$("#type_id").val();
			str=str.concat("?id=").concat(id);
			$('#delete').attr("href",str);
			});
	});
</script>
<script>
$(".breadcrumb").append("<li><a href='<?php echo $this->url->get("dashboard/list-banner");?>'>List Banner</a></li>");
</script>
<?php
if($this->request->get("type")!=NULL||$this->request->get("message")!=NULL) 
{
?>
 <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $this->request->get("type")?>">
       <?php echo $this->request->get("message"); ?>
 </p>
<?php }	?>
<form name="read_form" id="read_form" method="POST">
<div>
</div>
<div class="box-content">
						
						<table class="table table-striped table-bordered bootstrap-datatable">
						  <thead>
							  <tr>
                                  <th style="text-align:center;">Id</th>
                                  <th style="text-align:center;">Name</th>
                                  <th style="text-align:center;">Link</th>
                                  <th style="text-align:center;">Order</th>
                                  <th style="text-align:center;">Active</th>
                                  <th style="text-align:center;width: 150px;">Action</th>
							  </tr>
						  </thead>   
						  <tbody>
                          <?php $list_banner=$this->dispatcher->getParam("list_banner");
						  $total=$this->dispatcher->getParam("all_records");
						  foreach($list_banner as $banner){
						  ?>
                           <script>
                         	$(function(){
								$('#delete<?php echo $banner->getBannerId(); ?>').click(function (e) {
										e.preventDefault();
										$('#warn').modal('show');
										var id=$("#<?php echo $banner->getBannerId(); ?>").text();
										$("#type_id").val(id);
										var str="Are you sure to remove Banner ID = ".concat(id);
										$("#message").text(str);
										
										});
								});						 
                             </script>
                          	<tr>
                                <td style="text-align:center;"id="<?php echo $banner->getBannerId(); ?>"><?php echo $banner->getBannerId(); ?></td>
                                <td style="text-align:center;"class="center"><?php echo $banner->getBannerName(); ?></td>
                                <td style="text-align:left;"class="center"><?php echo $banner->getBannerLink(); ?></td>
                                <td style="text-align:center;"class="center"><?php echo $banner->getBannerOrder(); ?></td>
                                <td style="text-align:center;"class="center"><?php echo $banner->getBannerActive(); ?></td>
                                <td style="text-align:center;" class="center">
									<a id="edit_account" class="btn btn-info" href="<?php echo $this->url->get("dashboard/edit-banner");?>?id=<?php echo $banner->getBannerId(); ?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a id="delete<?php echo $banner->getBannerId();?>" class="btn btn-danger delete_account" href="#">										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
								</td>
							</tr>
                            <?php }?>
						  </tbody>
					  </table>    
                          <div class="pagination pagination-centered">
						  <ul>
                          <?php $crr_page=$this->dispatcher->getParam("current_page");
						  		 $total_page = $this->dispatcher->getParam("total_page");
						  ?>
                       
                          <?php if ($crr_page != 1){?>
							<li><a id="prev"  href="<?php echo $this->url->get('dashboard/list-banner')?>?page=<?php echo $crr_page-1;?>&active_search=<?php echo $active_search;?>">Prev</a></li>
                            <?php }?>
							<?php
							$n=floor($total_page/10);
							$b=$total_page%10;
							$flag=0;
							$limit=0;
							if($crr_page >=1){
								$flag=floor($crr_page/10);
								if($flag<$n){
									$limit=($flag*10)+10;
								}else{
									$limit=($flag*10)+$b;
								}
							}
							if($crr_page < $limit){
								$start=0;
								if($flag==0)
									$start=$flag*10+1;
								else
									$start=$flag*10;
								for($i=$start;$i <=$limit;$i++){
										if($i==$crr_page){
							 ?>
                             <li><a style="color:#333" id="number_page"  href="<?php echo $this->url->get('dashboard/list-banner')?>?page=<?php echo $i ?>&active_search=<?php echo $active_search;?>"><?php echo $i ?></a></li>
                             <?php }else{?>
                             <li><a id="number_page" href="<?php echo $this->url->get('dashboard/list-banner')?>?page=<?php echo $i ?>&active_search=<?php echo $active_search;?>"><?php echo $i ?></a></li>
                             		<?php }?>
                            	 <?php }?>
                             <?php }?>
                             <?php if ($crr_page<$total_page){?>
							<li><a id="next"  href="<?php echo $this->url->get('dashboard/list-banner')?>?page=<?php echo $crr_page+1;?>&active_search=<?php echo $active_search;?>">Next</a></li>
                            <?php }?>
						  </ul>
						</div> 
                        <p style="text-align:left;font-size:16px;color:red"><strong style="">Total : <?php  echo $total?></strong> Banners</p>

</div>
</form>

<!--FORM DELETE A TYPE-->

<form>
<div class="modal hide fade" id="warn">
	<div class="modal-header">
<input type="hidden" id="type_id" name="type_id" />
<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Warning !</h3>
	</div>
	<div class="modal-body">
				<p id="message"></p>
	</div>
	<div class="modal-footer">
				<a href="" class="btn" data-dismiss="modal">Close</a>
				<a id="delete" name="delete" href="" class="btn btn-primary">Yes</a>
	</div>
</div>
</form>